# Outcome extraction configuration
# This file controls case outcome detection, labeling, and metadata extraction

extraction:
  # Outcome detection patterns
  outcome_patterns:
    - pattern: "(?:granted|denied|dismissed|remanded|affirmed|reversed)"
      type: "disposition"
      confidence: 0.9

    - pattern: "(?:settlement|consent|decree|judgment)"
      type: "resolution"
      confidence: 0.8

    - pattern: "(?:\\$[0-9,]+(?:\\.[0-9]{2})?)"
      type: "cash_amount"
      confidence: 0.95

  # Case outcome categories
  categories:
    win: ["granted", "affirmed", "prevailing", "successful"]
    loss: ["denied", "dismissed", "reversed", "unsuccessful"]
    settlement: ["settlement", "consent decree", "agreed"]
    mixed: ["remanded", "partial", "mixed"]
    unknown: ["undetermined", "pending", "unclear"]

  # Label mapping and precedence
  label_precedence:
    - "win"
    - "loss"
    - "settlement"
    - "mixed"
    - "unknown"

labeling:
  # Label assignment rules
  rules:
    explicit_verbs:
      weight: 1.0
      patterns:
        - "granted summary judgment"
        - "denied motion to dismiss"
        - "affirmed district court"

    cash_indicators:
      weight: 0.8
      patterns:
        - "settlement amount"
        - "penalty of"
        - "fine of"
        - "award of"

    context_keywords:
      weight: 0.6
      patterns:
        - "plaintiff prevails"
        - "defendant prevails"
        - "case dismissed"

  # Minimum confidence thresholds
  min_confidence:
    win: 0.8
    loss: 0.8
    settlement: 0.7
    mixed: 0.6
    unknown: 0.0

cash_extraction:
  # Cash amount detection and parsing
  patterns:
    - "\\$[0-9]{1,3}(?:,[0-9]{3})*(?:\\.[0-9]{2})?"
    - "[0-9]{1,3}(?:,[0-9]{3})*(?:\\.[0-9]{2})? dollars?"
    - "penalty of [0-9]"
    - "fine of [0-9]"

  # Amount normalization
  normalization:
    convert_to_cents: true
    handle_ranges: "take_average"
    currency_symbols: ["$", "USD", "dollars"]

  # Amount validation
  validation:
    min_amount: 0
    max_amount: 1000000000  # 1 billion
    require_currency: false

metadata:
  # Additional metadata extraction
  extract:
    - "judge_name"
    - "court_name"
    - "case_number"
    - "decision_date"
    - "attorney_names"

  # Metadata patterns
  patterns:
    judge: "Judge ([A-Z][a-z]+(?: [A-Z][a-z]+)*)"
    court: "(?:Supreme Court|Court of Appeals|District Court)"
    case_number: "([0-9]{2}-[0-9]{4,6})"

imputation:
  # Missing data imputation
  enabled: true
  strategies:
    case_outcome: "majority_vote"
    cash_amount: "median"
    decision_date: "document_date"

  # Imputation sources
    - "document_text"
    - "citation_patterns"
    - "case_metadata"
    - "cross_references"

validation:
  # Output validation
  require_case_id: true
  require_label: true
  validate_label_confidence: true
  check_consistency: true
