# Text normalization configuration
# This file controls the text cleaning and normalization process

normalization:
  # Unicode normalization
  unicode_normalization: "NFKC"  # Options: NFC, NFD, NFKC, NFKD

  # Whitespace handling
  whitespace:
    normalize_spaces: true       # Convert multiple spaces to single space
    remove_leading_trailing: true # Remove leading/trailing whitespace
    normalize_line_breaks: true   # Convert \r\n to \n

  # Case handling
  case:
    lowercase: false             # Convert to lowercase (usually false for legal text)
    title_case: false            # Convert to title case

  # Punctuation handling
  punctuation:
    normalize_quotes: true       # Convert smart quotes to regular quotes
    normalize_dashes: true       # Convert em/en dashes to hyphens
    remove_repeated: false       # Remove repeated punctuation (e.g., !!! -> !)

  # Number and symbol handling
  numbers:
    normalize_ordinals: false    # Convert 1st, 2nd to 1, 2
    expand_ranges: false         # Convert 1-5 to "1 to 5"

  # Legal text specific
  legal:
    preserve_citations: true     # Keep citation formats intact
    preserve_case_names: true    # Keep proper case names
    normalize_court_names: false # Standardize court name formats

  # Content filtering
  filtering:
    remove_urls: false           # Remove URLs
    remove_emails: false         # Remove email addresses
    remove_phone_numbers: false  # Remove phone numbers
    remove_social_security: true # Remove SSN-like patterns

  # Offset mapping
  offsets:
    track_character_changes: true   # Track character-level changes
    track_word_changes: true        # Track word-level changes
    preserve_span_alignment: true   # Ensure spans can be mapped back

  # Performance settings
  performance:
    batch_size: 1000             # Documents to process at once
    max_document_length: 100000  # Maximum characters per document
    timeout_seconds: 300         # Timeout for single document processing

  # Logging and debugging
  debug:
    log_changes: false           # Log all text changes
    save_intermediates: false    # Save intermediate processing steps
    verbose_output: false        # Verbose console output
