# Example query configuration for corpus-api
# This file demonstrates the query DSL for fetching documents

sources:
  - courtlistener
  - rss
  - wikipedia

courtlistener:
  # Query parameters for CourtListener API
  date_range:
    start: "2020-01-01"
    end: "2023-12-31"

  courts:
    - "scotus"      # Supreme Court
    - "ca1"         # First Circuit
    - "ca2"         # Second Circuit

  case_types:
    - "civil"
    - "criminal"

  keywords:
    - "corporate"
    - "securities"
    - "antitrust"

  docket_numbers:
    - "123-456"
    - "789-012"

rss:
  # RSS feed sources
  feeds:
    - url: "https://www.sec.gov/rss/news/press"
      name: "SEC Press Releases"
    - url: "https://www.ftc.gov/rss/feed"
      name: "FTC News"

  filters:
    keywords: ["corporate", "merger", "antitrust"]

wikipedia:
  # Wikipedia scraping parameters
  pages:
    - "List_of_corporate_lawsuits"
    - "List_of_antitrust_cases"

  categories:
    - "Corporate_law"
    - "Antitrust_law"

output:
  format: "jsonl"
  include_metadata: true
  include_full_text: true

# Rate limiting and retry configuration
rate_limit:
  requests_per_minute: 60
  burst_limit: 10

retry:
  max_attempts: 3
  backoff_factor: 1.5
  retry_on_status: [429, 500, 502, 503, 504]
