# Working configuration for quote extraction with clean, normalized S&P 500 and Dow Jones data
# Only includes normalized columns with no numbers or special characters

config = {
    "nlp": {
        "spacy_model": "en_core_web_sm",
        "enable_ner": True,
        "use_gpu": False,
        "role_keywords": [
            "CHAIR",
            "CHAIRMAN",
            "CHAIRWOMAN",
            "COLGATE",
            "CORPORATION",
            "CPO",
            "CTO",
            "EXECUTIVE_CHAIRMAN",
            "FOUNDER",
            "PRESIDENT",
            "TREASURER",
        ],
        "executive_names": [
            "Aaron Jagdfeld",
            "Aaron Lufkin Dennison",
            "Aart de Geus",
            "Abhi Khandelwal",
            "Abhi Talwalkar",
            "Adaire Fox-martin",
            "Adam H. Schechter",
            "Adam Rymer",
            "Adam Satterfield",
            "Addison Rand",
            "Adena Friedman",
            "Advance Publications",
            "Ahmad Bahai",
            "Ajit Jain",
            "Al Avery",
            "Alan B. Miller",
            "Alan Campbell",
            "Alan D. Schnitzer",
            "Alan G. Hassenfeld",
            "Alan S. Armstrong",
            "Alan Shugart",
            "Albert Bourla",
            "Albert G. White",
            "Albert J. Neupaver",
            "Aldo J. Pagliari",
            "Alesia Haas",
            "Alex Chriss",
            "Alex Darbeloff",
            "Alex Karp",
            "Alex Manoogian",
            "Alexander J. Jessett",
            "Alexis L-quc",
            "Alfred P. Sloan Ceo",
            "Alice Marriott",
            "Allen J. Mistysyn",
            "Allen Rosenshine",
            "Allison Niderno",
            "Alok Maskara",
            "Alonzo G. Decker",
            "Altaf Rupani",
            "Alva Kinney",
            "Alvin B. Phillips",
            "Amory Houghton",
            "Amrita Ahuja",
            "Amy Woods Brinkley",
            "Anat Ashkenazi",
            "And Ceo",
            "And Chairman",
            "And J.r. Ridgway",
            "And President",
            "Anders Gustafsson",
            "Andr Calantzopoulos",
            "Andra Carter",
            "Andre Maciel",
            "Andrea Albertini",
            "Andrea J. Ayers",
            "Andres Gluski",
            "Andrew Anagnost",
            "Andrew Bosworth",
            "Andrew C. Florance",
            "Andrew Cecere",
            "Andrew Dennison",
            "Andrew Dickinson",
            "Andrew Florance",
            "Andrew Hider",
            "Andrew Mccollum",
            "Andrew P. Power",
            "Andrew Schlossberg",
            "Andrew Silvernail",
            "Andrew Viterbi",
            "Andrew Wiechmann",
            "Andrew Wilson",
            "Andrew Young",
            "Andrew drew Marsh",
            "Andy Bechtolsheim",
            "Andy Fang",
            "Andy Jassy",
            "Andy Saperstein",
            "Andy Sullivan",
            "Aneel Bhusri",
            "Angela L. Kleiman",
            "Anirudh Devgan",
            "Annette F. Favorite",
            "Anthony Capuano",
            "Anthony Carano",
            "Anthony Smurfit",
            "Antonio Neri",
            "April Arnzen",
            "Archibald Taft",
            "Ari Bousbib",
            "Ari Emanuel",
            "Ariane Gorin",
            "Armando Pimentel",
            "Arne Wilhelmsen",
            "Arnold Rosen",
            "Arthur Blank",
            "Arthur J. Gallagher",
            "Arthur J. Schmitt",
            "Arthur L. Parker",
            "Arthur Levinson",
            "Arthur Rock",
            "Arvind Krishna",
            "Asa Griggs Candler",
            "Aubrey Mcclendon",
            "Austin Church",
            "B. Thomas Golisano",
            "B. Wayne Hughes",
            "Badri Kothandaraman",
            "Baer Pettit",
            "Balazs Fejes Ceo President",
            "Bank Of America",
            "Barry Babcock",
            "Barry Diller",
            "Ben Tisch",
            "Benjamin G. Clark",
            "Benjamin Holt",
            "Benjamin Newton Duke",
            "Benjamin Schall",
            "Berkshire Hathaway",
            "Bernard Cammarata",
            "Bernard J. Birkett",
            "Bernard J. Zovighian",
            "Bernard Kroger",
            "Bernard Marcus",
            "Beth A. Costello",
            "Beth Whited",
            "Bill Amos",
            "Bill Bowerman",
            "Bill Dally",
            "Bill Fair",
            "Bill Fehrman",
            "Bill Gates",
            "Bill Grogan",
            "Bill Hornbuckle",
            "Bill Isackson",
            "Bill Krieger",
            "Bill Mcdermott",
            "Bill Nash",
            "Bill Newlands",
            "Bill Seidemann",
            "Bill W. Wheat",
            "Billy Gifford",
            "Blackrock",
            "Blake Moret",
            "Bob Fishman",
            "Bob Foster",
            "Bob Iger",
            "Bob Jordan",
            "Bob Kierlin",
            "Bob Miner",
            "Bob Parsons",
            "Bob Pragada",
            "Bob Sulentic",
            "Bow Ruggeri",
            "Brad Beckham",
            "Brad Greiwe",
            "Brad Jacobs",
            "Brad Smith",
            "Brad Trenkle",
            "Bradley S. Powell",
            "Brandon Sink",
            "Brendan Foley",
            "Brett Hart",
            "Brett Sandercock",
            "Brian Armstrong",
            "Brian Chesky",
            "Brian Cornell",
            "Brian D. Savoy",
            "Brian Delghiaccio",
            "Brian Doubles",
            "Brian Evanko",
            "Brian J. van Abel",
            "Brian L. Roberts",
            "Brian Moynihan",
            "Brian Niccol",
            "Brian S. Tyler",
            "Brian Sharples",
            "Brian X. Tierney",
            "Brje Ekholm",
            "Bruce Bodine",
            "Bruce Hansen",
            "Bruce Thompson",
            "Bruce van Saun",
            "Bryan D. Preston",
            "Bryan Hanson",
            "Bud Walton",
            "Burdett J. Johnson",
            "Byron L. Smith",
            "Byron Laflin Smith",
            "C. David Molina",
            "C. Nye",
            "C.b. Ames",
            "C.e. Woolman",
            "C.l. Best",
            "Cadwallader C. Washburn",
            "Cal Turner",
            "Caleb Bradham",
            "Calvin Butler",
            "Calvin Mcdonald",
            "Cam Weber",
            "Cameron M. Bready",
            "Campbell P. Brown",
            "Capital Research Global Investors",
            "Carl Eschenbach",
            "Carl Hess",
            "Carl von Linde",
            "Carlos Abrams-rivera",
            "Carlos M. Hernandez",
            "Carlyle And",
            "Carol B. Tom",
            "Carol Meyrowitz",
            "Caroline Dorsa",
            "Caroline Litchfield",
            "Carolyn Burke",
            "Carter H. Andrus",
            "Cator Woolford",
            "Cdo",
            "Cecil H. Green",
            "Cedric W. Burgher",
            "Celeste Burgoyne",
            "Ceo Founder",
            "Chad Richison",
            "Chair",
            "Chairman Of The Board",
            "Chairperson",
            "Charles Arnao",
            "Charles B. Clark",
            "Charles D. Mccrary",
            "Charles F. Erhart",
            "Charles F. Oreilly",
            "Charles G. Smith As",
            "Charles Geschke",
            "Charles H. Oreilly",
            "Charles Henry Robinson",
            "Charles Husband",
            "Charles Jeremiah Smith",
            "Charles K Vaughan",
            "Charles Kettering Director Of Research",
            "Charles Liang",
            "Charles M. Olcott",
            "Charles N. Felton",
            "Charles Pfizer",
            "Charles R. Schwab",
            "Charles Ranlett Flint",
            "Charles Scharf",
            "Charles Schmidt",
            "Charles Simmons",
            "Charles Snyder",
            "Charles Trimble Et Al",
            "Charles W. Brady",
            "Charles Weissmann",
            "Cheryl Norton",
            "Chicago Board Of Trade",
            "Chief Financial Officer",
            "Chip Bergh",
            "Chip Wilson",
            "Chris Boerner",
            "Chris Cocks",
            "Chris Concannon",
            "Chris Cox",
            "Chris Gorman",
            "Chris Hughes",
            "Chris Isaacson",
            "Chris Kempczinski",
            "Chris Kubasik",
            "Chris Malachowsky",
            "Chris Perry",
            "Chris Steddum",
            "Chris Suh",
            "Chris Viehbacher",
            "Chris Winfrey",
            "Chris Womack",
            "Christine Leahy",
            "Christophe Beck",
            "Christophe le Caillec",
            "Christopher A. Oherlihy",
            "Christopher D. Kastner",
            "Christopher Delorefice",
            "Christopher J. Nassetta",
            "Christopher J. Swift",
            "Christopher Payne",
            "Christopher T. Calio",
            "Chro",
            "Chuck Magro",
            "Chuck Robbins",
            "Clark Khayat",
            "Clay Gaspar",
            "Clay Holder",
            "Clessie Lyle Cummins",
            "Cliff Pemble",
            "Collis Potter Huntington",
            "Congdon Family",
            "Conor C. Flynn",
            "Conrad Hilton",
            "Conrad Schlumberger",
            "Corie Barry",
            "Cornelius Vander Starr",
            "Craig Arnold",
            "Craig Barratt",
            "Craig Billings",
            "Craig Donohue",
            "Craig Safian",
            "Crawford W. Beveridge",
            "Cristiano Amon",
            "Csar Cernuda",
            "Curtis Priem",
            "Cynthia T. Jamison",
            "D. Keith Oden",
            "D.g. Macpherson",
            "Dallas B. Tanner",
            "Dan Amos",
            "Dan Drake",
            "Dan Fisher",
            "Dan Letter",
            "Dan Simkowitz",
            "Daniel A. Carestio",
            "Daniel Cregg",
            "Daniel E. Pinto",
            "Daniel Guglielmone",
            "Daniel Hesse",
            "Daniel L. Florness",
            "Daniel Lewin",
            "Daniel Oday",
            "Daniel Tucker",
            "Dara Khosrowshahi",
            "Darius Adamczyk",
            "Darren Woods",
            "Daryl N. Bible",
            "Daryl Simm",
            "Dave Duffield",
            "Dave Gitlin",
            "Dave Lennox",
            "Dave Moellenhoff",
            "Dave Mosley",
            "Dave Pickles",
            "Dave Regnery",
            "Dave Rosa",
            "David A. Brandon",
            "David A. Jones",
            "David A. Montecalvo",
            "David A. Ricks",
            "David A. Zapico",
            "David Altshuler",
            "David Blitzer",
            "David Bowler",
            "David Bozeman",
            "David Campbell",
            "David Cheriton",
            "David Coors",
            "David Cordani",
            "David E. Simon",
            "David Elkins",
            "David Ellison",
            "David Evans Shaw",
            "David Faeder",
            "David G. Barnes",
            "David Gansberg",
            "David Gibbs",
            "David Gregory",
            "David Hitz",
            "David Howson",
            "David J. Neithercut",
            "David J. Turner",
            "David Joyner",
            "David K. Lam",
            "David Kenny",
            "David Lauren",
            "David Loo",
            "David M. Solomon",
            "David Marriott",
            "David Ossip",
            "David Rudd",
            "David Rumph",
            "David S. Congdon",
            "David Taylor",
            "David V. Auld",
            "David Weigand",
            "David Williams",
            "David Zaslav",
            "David Zinsner",
            "Dean Buntrock",
            "Deanna Strable",
            "Deborah Weitzman",
            "Debra Cafaro",
            "Dee Hock",
            "Deidra Merriwether",
            "Dennis Bakke",
            "Dennis Gillings",
            "Dennis Wilson",
            "Denson N. Franklin Iii",
            "Deon Stander",
            "Dermot Mcdonogh",
            "Derrick Rossi",
            "Devin Stockfish",
            "Diane Cafritz",
            "Dick George",
            "Dinos Iordanou",
            "Dirk van de Put",
            "Dmitri Alperovitch",
            "Domenic J. Dellosso",
            "Dominick Burke",
            "Dominick Devarti",
            "Don Allan",
            "Don Clegg",
            "Don Goodliffe",
            "Donald Baxter",
            "Donald C. Wood",
            "Donald F. Flynn",
            "Donald Knauss",
            "Donald Ray Horton",
            "Donnie King",
            "Doug Abbey",
            "Doug Brooks",
            "Doug Mahon",
            "Doug Mcmillon",
            "Doug Otto",
            "Doug Pitman",
            "Douglas Dayton And John Geisse",
            "Douglas T. Linde",
            "Douglas W. Peacock",
            "Dustin Moskovitz",
            "Dwight Schar",
            "E. R. Squibb",
            "E. Scott Santi",
            "Earl C. Austin",
            "Earl Congdon",
            "Earl Isaac",
            "Ed Bastian",
            "Ed Hill",
            "Ed Ho",
            "Ed Kaplan",
            "Ed Oates",
            "Eduardo F. Menezes",
            "Eduardo Saverin",
            "Edward B. Pitoniak",
            "Edward D. Breen",
            "Edward E. Rieck",
            "Edward H. Linde",
            "Edward Hughes",
            "Edward Mead Johnson",
            "Edward Philip",
            "Edward Temple",
            "Edward Williams",
            "Edwin Roks",
            "Elaine Wynn",
            "Eli Lilly",
            "Elisha Otis",
            "Elizabeth Betty Brinn",
            "Elizabeth E. Tallett",
            "Elliott Hill",
            "Elon Musk",
            "Emeritus",
            "Emilie Choi",
            "Enrique Lores",
            "Enrique Mayor-mora",
            "Erhard Mettler And Henry Theobald",
            "Eric Andersen",
            "Eric Ashleman",
            "Eric Chewning",
            "Eric M. Green",
            "Eric Pierson Swenson",
            "Eric Resnick",
            "Eric Zinterhofer",
            "Erik Fyrwald",
            "Erle P. Halliburton",
            "Ernie Herrman",
            "Este Lauder",
            "Ester Banque",
            "Eugene Bredow",
            "Eugene L. Batchelder",
            "Eugene Mcdermott",
            "Evan G. Greenberg",
            "Evan Moore",
            "Evan Scott",
            "Evelyn J. Clark",
            "Ezra Y. Yacob",
            "F. Thomson Leighton",
            "Fairleigh S. Dickinson",
            "Finis Conner",
            "Flemming rnskov",
            "Founding",
            "Frank D. Yeary",
            "Frank Dominguez",
            "Frank E. Dangeard",
            "Frank M. Svoboda",
            "Frank Phillips",
            "Frank Simuro",
            "Frank St. John",
            "Frank St. Romain",
            "Franklin Antonio",
            "Franois Locoh-donou",
            "Franois Morin",
            "Fred Ehrsam",
            "Fred Luddy",
            "Fred Rothman",
            "Frederick Rentschler",
            "Frederick Trent Stanley",
            "Frederick W. Smith",
            "Friedrich Weyerhuser",
            "Gail Koziara Boudreaux",
            "Gale Klappa",
            "Garrett Camp",
            "Garrick Rochow",
            "Gary Burrell",
            "Gary Carano",
            "Gary Cohn",
            "Gary E. Dickerson",
            "Gary Hendrix",
            "Gary Rollins",
            "Gary S. Guthart",
            "Gary Swidler",
            "Gavin Hattersley",
            "Gene Hall",
            "Geoff Martha",
            "Geoff Molson",
            "George A. Archer",
            "George A. Hormel",
            "George E. Cates",
            "George Eastman",
            "George Garvin Brown",
            "George Kao",
            "George Kozmetsky",
            "George Kurian",
            "George Kurtz",
            "George L. Miller",
            "George M. Marcus",
            "George Markus Loturco",
            "George Merck",
            "George R. Roberts",
            "George Winthrop Fairchild",
            "George Yancopoulos",
            "Gerben Bakker",
            "Gerhard Cless",
            "Gideon Gartner",
            "Glen Hauenstein",
            "Glenn D. Fogel",
            "Glenn G. Cohen",
            "Glenn Hubbard",
            "Global Clinical",
            "Gordon Bowker",
            "Gordon Gund",
            "Gordon Moore",
            "Governed By A -member Board Of Trustees. Sanford Cloud",
            "Greg Abel",
            "Greg Brown",
            "Greg Case",
            "Greg Heckman",
            "Greg Maffei",
            "Greg Penner",
            "Greg Peters",
            "Gregg Brummer",
            "Gregg Marston",
            "Gregory E. Johnson",
            "Gregory Ebel",
            "Gregory H. Boyce",
            "Gregory Hebard",
            "Gregory J. Hayes",
            "Gregory Plemmons",
            "Gunjan Kedia",
            "Gus Blanchard",
            "Guy Woolford",
            "H Lynn Moore Jr",
            "H. Edward Hanway",
            "H. Eric Bolton",
            "H. Lawrence Culp",
            "H.m. Byllesby",
            "Hal Lawton",
            "Hamid Moghadam",
            "Hamilton E. James",
            "Hans Vestberg",
            "Harold Stanley",
            "Harris Fricker",
            "Harry Rosenthal",
            "Harry Sideris",
            "Harry Sommer",
            "Harvey Hubbell",
            "Hassane El-khoury",
            "Havilah Babcock",
            "Haviv Ilan",
            "Heath Monesmith",
            "Heidi G. Petz",
            "Heinz Schaller",
            "Helen L. Shan Cfo",
            "Henry A. Fernandez",
            "Henry Ford",
            "Henry Hassenfeld",
            "Henry Kravis",
            "Henry Orth Hirt",
            "Henry R. Kravis",
            "Henry S. Bryan",
            "Henry Samueli",
            "Henry Schein",
            "Henry Sherwin",
            "Henry Singleton",
            "Henry Sturgis Morgan",
            "Henry Taub",
            "Henry Wells",
            "Henry Willis",
            "Herb Kelleher",
            "Herbert Henry Dow",
            "Herbert Irving",
            "Herbert Simon",
            "Herman Hassenfeld",
            "Herman Hollerith",
            "Hermon W. Cable",
            "Herv Hoppenot",
            "Hillel Hassenfeld",
            "Hilton Schlosberg",
            "Hock Tan",
            "Holden Lewis",
            "Homer Stryker",
            "Howard Schultz",
            "Howard Wille",
            "Howard Wood",
            "Howard Y. Chang",
            "Hubert Hansen",
            "Hugh J. Chisholm",
            "Inga Beale",
            "Irving Tan",
            "Irwin Jacobs",
            "Isabella Pirzadeh",
            "Itero Scanner And Services Business",
            "Ivan Tornos",
            "J. Danley Budd",
            "J. Eric Bjornholt",
            "J. Erik Jonsson",
            "J. Hyatt Brown",
            "J. Kevin Akers",
            "J. Larry Nichols",
            "J. Patrick Gallagher",
            "J. Powell Brown",
            "J. Robert Bob Beyster",
            "J. Thomas Hill",
            "J. Willard Marriott",
            "Jacek Olczak",
            "Jack C. Massey",
            "Jack Dorsey",
            "Jack Dorsey Chair",
            "Jack Henry",
            "Jack Henry Jerry Hall",
            "Jamere Jackson",
            "James Bidzos",
            "James Buchanan Duke",
            "James C. Fish",
            "James C. Foster",
            "James Conroy",
            "James E. Casey",
            "James F. Risoleo",
            "James Ford Bell",
            "James Gamble",
            "James Golden",
            "James H. Mcgraw",
            "James Hackett",
            "James Hippel",
            "James L. Ossowski",
            "James Lau",
            "James Logan Waters",
            "James Luther Turner",
            "James M. Cracchiolo",
            "James P. Gorman",
            "James R. Chapman",
            "James S. Kuhn",
            "James Sinegal",
            "James Snee",
            "James Solomon",
            "James Taiclet",
            "James Tisch",
            "James Wheeler",
            "James Wood Johnson",
            "Jamey Mock",
            "Jamie Caulfield",
            "Jamie Dimon",
            "Jamie Iannone",
            "Jane Fraser",
            "Janice Chaffin",
            "Jason Hollar",
            "Jason Liberty",
            "Jason P. Wells",
            "Jason S. Armstrong",
            "Jasper Rand",
            "Javier J. Rodriguez",
            "Javier Olivan",
            "Jay A. Stein Chairman-emeritus",
            "Jay Adair",
            "Jay Adelson",
            "Jay Mazelsky",
            "Jay Morse",
            "Jay S. Walker",
            "Jayshree Ullal",
            "Jeff Bezos",
            "Jeff Clarke",
            "Jeff Green",
            "Jeff Henley",
            "Jeff Howie",
            "Jeff Liaw",
            "Jeff Miller",
            "Jeff Noddle",
            "Jeff Shell",
            "Jeff Tate",
            "Jeffrey A. Goldstein",
            "Jeffrey A. Stoops",
            "Jeffrey B. Guldner",
            "Jeffrey Brotman",
            "Jeffrey Edwards",
            "Jeffrey Harmening",
            "Jeffrey Kaplan",
            "Jeffrey L. Ritenour",
            "Jeffrey Leiden",
            "Jeffrey Lorberbaum",
            "Jeffrey Sprecher",
            "Jeffrey W. Martin",
            "Jennifer A. Parmentier",
            "Jennifer M. Johnson",
            "Jennifer Piepszak",
            "Jennifer Rumsey",
            "Jensen Huang",
            "Jerald Kent",
            "Jeremy Knop",
            "Jerome Kohlberg",
            "Jerome Monroe Smucker",
            "Jerry Baldwin",
            "Jerry E. Gahlhoff",
            "Jerry M. Sudarsky",
            "Jerry Sanders",
            "Jill Griebenow",
            "Jim Burke",
            "Jim Davis",
            "Jim Farley",
            "Jim Fitterling",
            "Jim Lyski",
            "Jim Mckelvey",
            "Jim Monaghan",
            "Jim Nickolas",
            "Jim Rechtin",
            "Jim Turley",
            "Jim Umpleby",
            "Jim Vena",
            "Jim Williamson",
            "Jim Zelter",
            "Joakim Weidemanis",
            "Joanne Crevoiserat",
            "Joaquin Duato",
            "Jodee Kozlak",
            "Joe Creed",
            "Joe Gebbia",
            "Joe Hogan",
            "Joe Lonsdale",
            "Joe Parkinson",
            "Joel Grade",
            "Joel S. Marcus",
            "Johann P. G. Bunge",
            "John A. Hill",
            "John A. Kimberly",
            "John Abele",
            "John Amos",
            "John Ayala",
            "John Baptiste Ford",
            "John Bernbach",
            "John C. Dugan",
            "John C. Griffith",
            "John C. Malone",
            "John C. May",
            "John C. Plant",
            "John Crosby",
            "John D. Wren",
            "John Deere",
            "John Donahoe",
            "John Dwan",
            "John Dwight",
            "John E. Stokely",
            "John F. Baugh",
            "John F. Dryden",
            "John F. Lundgren",
            "John F. Morici",
            "John F. Wilson",
            "John G. Morikis",
            "John Gibson",
            "John H. Tyson",
            "John Hoke",
            "John J. Christmann Iv",
            "John J. Schiff",
            "John J. Zillmer",
            "John Klinger",
            "John Kuhlow",
            "John L. Hennessy",
            "John L. Stauch",
            "John M. Pasquesi",
            "John M. Turner",
            "John Mckesson",
            "John Moody",
            "John Murphy",
            "John N. Roberts",
            "John Nichols",
            "John Olin Executive Vice President And Cfo",
            "John P. Nallen",
            "John P. Surma",
            "John Philip Holland",
            "John Pitcairn",
            "John Q. Doyle",
            "John Reay Ceo",
            "John Rex",
            "John Ripley Myers",
            "John S. Marr Jr",
            "John Stankey",
            "John Stone",
            "John T. Cahill",
            "John Tappan",
            "John Towers",
            "John W. Daniels",
            "John W. Emerson",
            "John W. Gamble",
            "John W. Garratt",
            "John W. Ketchum Chairman",
            "John W. Rollins",
            "John W. Stanton",
            "John W. Tyson",
            "John Walker",
            "John Warnock",
            "John Zito",
            "Johnelle Hunt",
            "Johnnie Bryan Hunt",
            "Joi Harris",
            "Jon Jaffe",
            "Jon Monson",
            "Jon R. Moeller",
            "Jon Vander Ark",
            "Jonathan D. Gray",
            "Jonathan Gray",
            "Jonathan Pong",
            "Jonathan Seelig",
            "Joseph A. Campbell",
            "Joseph Bae",
            "Joseph Baratta",
            "Joseph D. Fisher",
            "Joseph D. Margolis",
            "Joseph D. Russell",
            "Joseph Dominguez",
            "Joseph F. Mckinney",
            "Joseph Forline",
            "Joseph J. Jacobs",
            "Joseph Johnson",
            "Joseph Lauder",
            "Joseph Oriel Eaton",
            "Joseph R. Hinrichs",
            "Joseph R. Nolan",
            "Joseph V. Taranto",
            "Joseph Zubretsky",
            "Josh Harris",
            "Joshua Isner",
            "Joshua Weinstein",
            "Juan Luciano",
            "Judy Marks",
            "Julia L. Johnson",
            "Julie Edwards",
            "Julie Sweet",
            "Justin Jude",
            "Justin Leong",
            "Justin O. Zimmer",
            "K. Gunnar Bjorklund",
            "Kaes Vant Hof",
            "Karen L. Parkhill",
            "Karim Boussebaa",
            "Karl F. Kurz",
            "Karl F. Lopker",
            "Karl Slatoff",
            "Karleen Marie Oberton",
            "Kathleen L. Quirk",
            "Kathy J. Warden",
            "Katrin Pucknat",
            "Kazuo Okada",
            "Kecia Steelman",
            "Keith J. Allman",
            "Keith Jensen",
            "Keith W. Demmings",
            "Kelly Mahon Tullier",
            "Kelly Ortberg",
            "Kelsey Wirth",
            "Kelvin O. Moses",
            "Ken Howery",
            "Ken Langone",
            "Ken Xie",
            "Kenneth Duda",
            "Kenneth Murray",
            "Kenneth R. Chien",
            "Kenneth Volk",
            "Kenneth Woolley",
            "Kent Masters",
            "Kevin A. Lobo",
            "Kevin Hourican",
            "Kevin J. Pearson",
            "Kevin J. Wheeler",
            "Kevin Marty Freeman",
            "Kevin P. Clark",
            "Kevin P. Oshea",
            "Kevin Sayer",
            "Kevin Stein",
            "Kim Kelderman",
            "Kim R Cocklin",
            "Kimberly A. Dang",
            "Kimberly J. Harris",
            "Kirk Kerkorian",
            "Kirk Perry",
            "Kirkland H. Donald",
            "Koh Boon Hwee",
            "Kristin Peck",
            "Kumar Mahadeva",
            "Kurt J. Hilzinger",
            "Kurt Sievers",
            "L.e. Phillips",
            "Lachlan Murdoch",
            "Lainie Goldstein",
            "Lal Karsanbhai",
            "Lane Riggs",
            "Larry Coben",
            "Larry Ellison",
            "Larry Fink",
            "Larry Merlo",
            "Larry Page",
            "Later",
            "Laura Alber",
            "Laura Miele",
            "Lauren Peters",
            "Laurence K. Marshall",
            "Laurie P. Havanec",
            "Lavanya Chandrashekar",
            "Lawrence D. Mcrae",
            "Lawrence Kingsley",
            "Lawson E. Whiting",
            "Lawton W. Fitt",
            "Lee Raymond",
            "Lee Shavel",
            "Leon Black",
            "Leon Topalian",
            "Leonard Bosack",
            "Leonard Lenny Singh",
            "Leonard Miller",
            "Leonard P. Pool",
            "Leonard Schleifer",
            "Lester Knight",
            "Liberty Media",
            "Lillian Congdon",
            "Linda Filler Jennifer L. Honeycutt",
            "Linda Rendle",
            "Lip-bu Tan",
            "Lisa Palmer",
            "Lisa Ruggles",
            "Lisa Su",
            "Lloyd Tevis",
            "Lloyd Yates",
            "Lon R. Greenberg",
            "Lorenzo Simonelli",
            "Lori Koch",
            "Lori Sutton",
            "Louise S. Sams",
            "Lucio Noto",
            "Lucius Smith Lowe",
            "Luke Nosek",
            "Lydia Beebe",
            "Lynn Martin",
            "Lynne Fitzpatrick",
            "Maamoun Rajeh",
            "Malcolm Fraser",
            "Manuel Kadre",
            "Marc Benioff",
            "Marc D. Miller",
            "Marc E. Binda",
            "Marc N. Casper",
            "Marc Randolph",
            "Marc Rowan",
            "Marc Tarpenning",
            "Marcel Schlumberger",
            "Marcus Goldman",
            "Margaret M. Keane",
            "Maria Black",
            "Mark C. Birk",
            "Mark C. Honeywell",
            "Mark C. Pigott",
            "Mark D. Mclaughlin",
            "Mark D. Millett",
            "Mark G. Papa",
            "Mark J. Costa",
            "Mark J. Parrell",
            "Mark Keim",
            "Mark L. Feidler",
            "Mark Lashier",
            "Mark Mason",
            "Mark Mondello",
            "Mark Papermaster",
            "Mark Parker",
            "Mark R. George",
            "Mark Reuss",
            "Mark Shapiro",
            "Mark Smith",
            "Mark Smucker",
            "Mark W. Begor",
            "Mark W. Kowlzan",
            "Mark Widmar",
            "Mark Zenuk",
            "Mark Zuckerberg",
            "Martin E. Stein Jr",
            "Martin Eberhard",
            "Martin Fornage",
            "Martin J. Lyons",
            "Martin Kimmel",
            "Martina Cheung",
            "Marvin Ellison",
            "Marvin Sands",
            "Mary Hogan Preusse",
            "Maryann Mannen",
            "Matthew Benger",
            "Matthew Darden",
            "Matthew Flannery",
            "Matthew J. Meloy",
            "Matthew J. White",
            "Matthew Lorber",
            "Matthew Pine",
            "Max Broden",
            "Max Levchin",
            "Maxwell Becton",
            "Meghan Frank",
            "Melanie M. Housey Hart",
            "Melvin Simon",
            "Merit Janow",
            "Merritt J. Osborn",
            "Michael A. Mcneilly",
            "Michael And Obediah Haymaker",
            "Michael Balmuth",
            "Michael C. Creedon",
            "Michael D. Hsu",
            "Michael D. Mckee",
            "Michael Dell",
            "Michael Devine",
            "Michael Durand",
            "Michael Ettinger",
            "Michael F. Johnston",
            "Michael F. Mahoney",
            "Michael F. Roman",
            "Michael G. Ogrady",
            "Michael J. Ahearn",
            "Michael J. Cavanagh",
            "Michael J. Hartshorn",
            "Michael J. Hennigan",
            "Michael J. Mas",
            "Michael Kneeland",
            "Michael Krasny",
            "Michael L. Marberry",
            "Michael L. Moehn",
            "Michael L. Riordan",
            "Michael M. Calbert",
            "Michael Maguire",
            "Michael Malcolm",
            "Michael Mccallister",
            "Michael Mcmurray",
            "Michael Mick Farrell",
            "Michael Miebach",
            "Michael P. Lyons",
            "Michael R. Cannon",
            "Michael R. Hsing",
            "Michael Rapino",
            "Michael Rider",
            "Michael Sentonas",
            "Michael Wichterich",
            "Michael Xie",
            "Michel A. Khalaf",
            "Michel Lagarde",
            "Michele Buck Chairwoman",
            "Mick Beekhuizen",
            "Micky Arison",
            "Miguel Patricio",
            "Mike Baughman",
            "Mike Dastoor",
            "Mike Fliss",
            "Mike Guhl",
            "Mike Lyons",
            "Mike Mccarthy",
            "Mike Mcmullen",
            "Mike Nevens",
            "Mike Sievert",
            "Mike Thompson",
            "Mike Wirth",
            "Milan Galik",
            "Miller Williams",
            "Milton Cooper",
            "Milton S. Hershey",
            "Mimi Carsley",
            "Min Kao",
            "Mitch Butier",
            "Mitchell Rales",
            "Mitra Derakhshan",
            "Mj Holthaus",
            "Mohit Singh",
            "Mondelez International",
            "Morris Ross",
            "Mortimer Zuckerman",
            "N. Thomas Linebarger",
            "Naftali Holtz",
            "Named After",
            "Nathan Blecharczyk",
            "Neil Barua",
            "Neil Hunn",
            "Nicholas Furia",
            "Nick Dewolf",
            "Nicolas Papadopoulo",
            "Nigel Morris",
            "Nikesh Arora",
            "Nir Zuk",
            "Noel Wallace",
            "Noubar Afeyan",
            "O. Wayne Rollins",
            "Of The Board",
            "Oliver Chace",
            "Oliver Jenkyn",
            "Olivier Leonetti",
            "Olivier Pomel",
            "Olivier le Peuch",
            "Ollie G. Crawfordin",
            "Olumide Soroye",
            "Original Restaurant Chain",
            "Owen D. Thomas",
            "P.w. Huntington",
            "Padraig Mcdonnell",
            "Parker Harris",
            "Pat Farrah",
            "Patrice Louvet",
            "Patricia L. Kampling",
            "Patricia Russo",
            "Patrick Casey",
            "Patrick Desbois",
            "Patrick Dumont",
            "Patrick E. Haggerty",
            "Patrick Kaltenbach",
            "Patrick M. Gallagher",
            "Patrick Ryan",
            "Patrick W. Smith",
            "Patti Poppe",
            "Paul Allen",
            "Paul Amos",
            "Paul Brown",
            "Paul Donahue Executive",
            "Paul Ingrey",
            "Paul J. Romanowski",
            "Paul Pressler",
            "Paul Reilly",
            "Paul Salem",
            "Paul Saville",
            "Paul Shoukry",
            "Paul Thomas",
            "Paulo Pisano",
            "Paulo Ruiz",
            "Pedro J. Pizarro President And",
            "Peter A. Appel",
            "Peter Arduini",
            "Peter Bonfield",
            "Peter C. Farrell",
            "Peter D. Arvan",
            "Peter J. Millones",
            "Peter Jackson",
            "Peter Kenny",
            "Peter Konieczny",
            "Peter Nicholas",
            "Peter Peterson",
            "Peter Thiel",
            "Peter Vanacker",
            "Peter Zaffino",
            "Phebe Novakovic",
            "Phil Daniele",
            "Phil Knight",
            "Philip Angelastro",
            "Philip Brace",
            "Philip Carter",
            "Philip Knight",
            "Philip Morris",
            "Philipp Hildebrand",
            "Philippe Krakowsky",
            "Phillip Allen Sharp",
            "Pierce Norton",
            "Pierre Omidyar",
            "Pierre S. Du Pont Chairman Of The Board",
            "Pitt Hyde",
            "Prabir Adarkar",
            "Prahlad Singh",
            "Preetish Nijhawan",
            "President",
            "Preston Feight",
            "Quintin J. Lai",
            "R. Adam Norwitt",
            "R. Stanton Avery",
            "Rafael Santana",
            "Raghu Belur",
            "Rainer Blair",
            "Raj Subramaniam",
            "Ralph J. Roberts",
            "Ralph Larossa",
            "Ralph Lauren",
            "Ralph P. Hoagland",
            "Ramon Laguarta",
            "Randall Kaplan",
            "Randy Hyzak",
            "Randy Peck",
            "Ravi Inukonda",
            "Ravi Kumar Singisetti",
            "Ray Kroc",
            "Ray Stata",
            "Raymond Plank",
            "Raymond W. Mcdaniel",
            "Raytheon",
            "Rebecca J. Kujawa",
            "Redbird Capital Partners",
            "Reed Hastings",
            "Rejji Hayes",
            "Ren F. Jones",
            "Reshma Kewalramani",
            "Reubens Watson",
            "Rich Barton",
            "Richard A. Gonzalez",
            "Richard Adkerson",
            "Richard D. Kinder",
            "Richard Dierker",
            "Richard E. Marriott",
            "Richard Fairbank",
            "Richard Farmer",
            "Richard J. Campo",
            "Richard J. Daly",
            "Richard J. Tobin",
            "Richard Kinder",
            "Richard M. Schulze",
            "Richard Manoogian",
            "Richard Maurice Mcdonald",
            "Richard Mcvey",
            "Richard Newton",
            "Richard P. Wallace",
            "Richard Sands",
            "Richard Stoddart",
            "Richard T. Burke",
            "Rick Cardenas",
            "Rick Wagoner",
            "Rick Wurster",
            "Rob Fauber",
            "Rob Sands",
            "Rob Sharps",
            "Robert A. Bradway",
            "Robert A. Garechana",
            "Robert B. Ford",
            "Robert Blue",
            "Robert C. Frenzel",
            "Robert C. Schiff",
            "Robert Calderoni",
            "Robert Clements",
            "Robert D. Walter",
            "Robert E. Switz",
            "Robert Flexon",
            "Robert Funck",
            "Robert G. Goldstein",
            "Robert Gamgort",
            "Robert Gardner",
            "Robert Ingersoll Ingalls",
            "Robert J. Mylod",
            "Robert James",
            "Robert James Thomson",
            "Robert Kern",
            "Robert M. Davis",
            "Robert Mauch",
            "Robert Mehrabian",
            "Robert Michael",
            "Robert Noyce",
            "Robert Painter",
            "Robert S. Kapito",
            "Robert S. Langer",
            "Robert Schrader",
            "Robert Smith",
            "Robert Stiller",
            "Robert T. Oshaughnessy",
            "Robert V. Baumgartner",
            "Robert W. Hau",
            "Robert Wood Johnson I",
            "Robyn Denholm",
            "Rochelle Tarlowe",
            "Rodney Sacks",
            "Roger C. Lucas",
            "Roger Sant",
            "Roger W. Ferguson",
            "Rollin King",
            "Ron Brill",
            "Ron Nersesian",
            "Ron Sargent",
            "Ron Vachris",
            "Ronald F. Clarke",
            "Ronald L. Havner",
            "Ronald N. South",
            "Ronald P. Ohanley",
            "Ronald Sugar",
            "Ronald Wayne",
            "Roy O. Disney",
            "Royal Little",
            "Rufus Myers",
            "Rupert H. Johnson",
            "Rupert Murdoch",
            "Russell Weiner",
            "Ruth Porat",
            "Ryan Brant",
            "Ryan C. Haynes",
            "Ryan Lance",
            "Ryan Mcinerney",
            "Ryan R. Marshall",
            "Ryan Snyder",
            "S. Duncan Black",
            "Sachin Mehra",
            "Safra Catz",
            "Sam Hazen",
            "Sam Walton",
            "Sam Zell",
            "Sameer Hassan",
            "Sameer Ralhan",
            "Samuel Dipiazza",
            "Samuel J. Gorlitz",
            "Samuel Ramsden",
            "Samuel Sachs",
            "Sandy Lerner",
            "Sanjay Mehrotra President Ceo",
            "Sanjiv Lamba",
            "Sanoke Viswanathan Ceo",
            "Sara Liu",
            "Sarah London",
            "Sasan Goodarzi",
            "Sassine Ghazi",
            "Satish Dhanasekaran",
            "Satya Nadella",
            "Schwanna Ferguson",
            "Sco",
            "Scott A. Smith",
            "Scott A. Tozier",
            "Scott Boatwright",
            "Scott C. Donnelly",
            "Scott Cook",
            "Scott Crum",
            "Scott D. Farmer",
            "Scott Kirby",
            "Scott Kleinman",
            "Scott M. Brinker",
            "Scott Maw",
            "Scott Nuttall",
            "Scott Roe",
            "Scott Strazik",
            "Sean Connolly",
            "See",
            "Sergey Brin",
            "Seth Allen",
            "Shamim Mohammad",
            "Shane Hadlock",
            "Shankh Mitra",
            "Shantanu Narayen",
            "Sharmistha shar Dubey",
            "Sharon Yeshaya",
            "Shawn E. Schukar",
            "Shawn Vadala",
            "Sheldon G. Adelson",
            "Shelley Simpson",
            "Sidney Goldstein",
            "Silji Abraham",
            "Simon Ingersoll",
            "Sourav Ghosh",
            "Spencer Rascoff",
            "Stacy Mitchell",
            "Stanley J. Sutula",
            "Stanley M. Bergman",
            "Stanley P. Goldstein",
            "Stanley Tang",
            "Stefano Caroti",
            "Stephanie Ferris",
            "Stephen Cohen",
            "Stephen D. Steinour",
            "Stephen Hoge",
            "Stephen J. Hemsley",
            "Stephen M. Spray",
            "Stephen Mason",
            "Stephen P. Macmillan Chairman",
            "Stephen Schwarzman",
            "Stephen Squeri",
            "Steve Angel",
            "Steve Ells",
            "Steve G. Filton",
            "Steve Jobs",
            "Steve Laxton",
            "Steve Mollenkopf",
            "Steve Sanghi",
            "Steve Wozniak",
            "Steve Wynn",
            "Steven Black",
            "Steven Cahillane",
            "Steven H. Collis",
            "Steven Rales",
            "Steven Vondran",
            "Steven Voskuil Svp",
            "Stphane Bancel",
            "Stphane de la Faverie",
            "Strauss Zelnick",
            "Stuart M. Mcguigan",
            "Stuart Miller",
            "Sumeet Singh",
            "Sumit Roy",
            "Sun Choe",
            "Sundar Pichai",
            "Sundaram Nagarajan",
            "Supervisory Board",
            "Susan Diamond",
            "Susan Smith",
            "Susan Wagner",
            "Suzanne H. Wood",
            "Suzanne Nora Johnson",
            "Syed Iftikar",
            "T. Robert Burke",
            "Takis Georgakopoulos",
            "Team Led By",
            "Ted Arison",
            "Ted Decker",
            "Ted Grace",
            "Ted Pick",
            "Ted Sarandos",
            "Terrence A. Duffy",
            "Terrence Curtin",
            "Terry Hanson",
            "Thad Trent",
            "Theodore Weicker",
            "Theresa E. Wagler",
            "Thomas B. Hagen",
            "Thomas Bell",
            "Thomas Caldecot Chubb",
            "Thomas E. Jorden",
            "Thomas F. Frist",
            "Thomas H. Mcinnerney",
            "Thomas J. Gallagher",
            "Thomas J. Iannotti",
            "Thomas J. Mcinerney",
            "Thomas J. Wilson",
            "Thomas P. Smith",
            "Thomas Peterffy",
            "Thomas R. Palmer",
            "Thomas Reeg",
            "Thomas Rowe Price",
            "Thomas W. Toomey",
            "Tim Archer",
            "Tim Arndt",
            "Tim Cawley",
            "Tim Cofer",
            "Tim Cook",
            "Tim Gokey",
            "Tim Knavish",
            "Tim Noel",
            "Timotheus Httges",
            "Timothy A. Springer",
            "Timothy G. Necastro",
            "Timothy J. Naughton",
            "Timothy J. Scannell",
            "Timothy K. Driggers",
            "Timothy N. Spence",
            "Timothy Oconnor",
            "Toby Rice",
            "Todd Schneider",
            "Todd Vasos",
            "Tom Cihl",
            "Tom James",
            "Tom L. Ward",
            "Tom Martin",
            "Tom Mitchell",
            "Tom Monaghan",
            "Tom Polen",
            "Tom Popeck",
            "Tom Proulx",
            "Tony Ressler",
            "Tony Skiadas",
            "Tony Will",
            "Tony Xu",
            "Tracy Skeans",
            "Travis Kalanick",
            "Tricia Griffith",
            "Trip Hawkins",
            "Tristan Otierney",
            "Truman Anderson",
            "Tyler Glover",
            "Udit Batra",
            "United Technologies",
            "Vacant",
            "Vannevar Bush",
            "Vice-president",
            "Vicente Reynal",
            "Vicki Hollub",
            "Victor L. Richey",
            "Viggo Torbensen",
            "Vimal Kapur",
            "Viswas Raghavan",
            "W. K. Kellogg Foundation",
            "W. Nicholas Howley",
            "W. Robert Berkley",
            "W.s. Kuhn",
            "Wallace Calvin Abbott",
            "Walt Disney",
            "Walter G. Nord",
            "Walter Gilbert",
            "Walter S. Berman",
            "Walter Varney",
            "Ward Parkinson",
            "Warren Buffett",
            "Warren Gardiner",
            "Warren S. Johnson",
            "Wayne Huizenga",
            "Wayne T. Smith",
            "Wendell Cherry",
            "Wendell P. Weeks",
            "Will Keith Kellogg",
            "Will Stengel",
            "William A. Mcgonagle",
            "William A. Russell",
            "William Boyce Thompson",
            "William Burns",
            "William C. Durant",
            "William Clay Ford",
            "William Colgate",
            "William Darden",
            "William E. Boeing",
            "William E. Clark",
            "William E. Morean",
            "William Fargo",
            "William Glanton Irwin",
            "William Greehey",
            "William H. Rogers Jr",
            "William Hussey",
            "William J. Peet And Robert Peet",
            "William J. Pulte",
            "William Kennard",
            "William Lansing",
            "William M. Brown",
            "William Mclaren Bristol",
            "William Meaney",
            "William P. Lauder",
            "William Pigott",
            "William Procter",
            "William R. Berkley",
            "William R. Johnson",
            "William S. Demchak",
            "William V. Morgan",
            "William Wallace Grainger",
            "Willis Carrier",
            "Willis J. Johnson",
            "Willoughby Mccormick",
            "Yu Pan",
            "Zachary Hudson",
            "Zachary Wasserman",
            "Zev Siegl",
            "Zia Chishti",
        ],
    },
    "extraction": {
        "company_aliases": [
            "a. o. smith",
            "aapl",
            "abbott laboratories",
            "abbv",
            "abbvie",
            "abnb",
            "abt",
            "accenture",
            "acgl",
            "acn",
            "adbe",
            "adi",
            "adm",
            "adobe inc",
            "adp",
            "adsk",
            "advanced micro devices",
            "aee",
            "aep",
            "aes",
            "aes corporation",
            "afl",
            "aflac",
            "agilent technologies",
            "aig",
            "air products",
            "airbnb",
            "aiz",
            "ajg",
            "akam",
            "akamai technologies",
            "alb",
            "albemarle corporation",
            "alexandria real estate equities",
            "algn",
            "align technology",
            "all",
            "alle",
            "allegion",
            "allstate",
            "alphabet inc",
            "altria",
            "amat",
            "amazon",
            "amcor",
            "amcr",
            "amd",
            "ame",
            "ameren",
            "american electric power",
            "american express",
            "american international group",
            "american tower",
            "american water works",
            "ameriprise financial",
            "ametek",
            "amgen",
            "amgn",
            "amp",
            "amphenol",
            "amt",
            "amzn",
            "analog devices",
            "anet",
            "aon",
            "aon plc",
            "aos",
            "apa",
            "apa corporation",
            "apd",
            "aph",
            "apo",
            "apollo global management",
            "apple inc",
            "applied materials",
            "aptiv",
            "aptv",
            "arch capital group",
            "archer daniels midland",
            "are",
            "arista networks",
            "arthur j. gallagher & co",
            "assurant",
            "at&t",
            "atmos energy",
            "ato",
            "autodesk",
            "automatic data processing",
            "autozone",
            "avalonbay communities",
            "avb",
            "avery dennison",
            "avgo",
            "avy",
            "awk",
            "axon",
            "axon enterprise",
            "axp",
            "azo",
            "ba",
            "bac",
            "baker hughes",
            "ball",
            "ball corporation",
            "bank of america",
            "bax",
            "baxter international",
            "bby",
            "bdx",
            "becton dickinson",
            "ben",
            "berkshire hathaway",
            "best buy",
            "bf.b",
            "bg",
            "biib",
            "bio-techne",
            "biogen",
            "bk",
            "bkng",
            "bkr",
            "blackrock",
            "blackstone inc",
            "bldr",
            "blk",
            "block inc",
            "bmy",
            "bny mellon",
            "boeing",
            "booking holdings",
            "boston scientific",
            "br",
            "bristol myers squibb",
            "brk.b",
            "bro",
            "broadcom",
            "broadridge financial solutions",
            "brown & brown",
            "brownforman",
            "bsx",
            "builders firstsource",
            "bunge global",
            "bx",
            "bxp",
            "bxp inc",
            "c.h. robinson",
            "cadence design systems",
            "caesars entertainment",
            "cag",
            "cah",
            "camden property trust",
            "campbell's company the",
            "capital one",
            "cardinal health",
            "carmax",
            "carnival",
            "carr",
            "carrier global",
            "cat",
            "caterpillar inc",
            "cb",
            "cboe",
            "cboe global markets",
            "cbre",
            "cbre group",
            "ccl",
            "cdns",
            "cdw",
            "cdw corporation",
            "ceg",
            "cencora",
            "centene corporation",
            "centerpoint energy",
            "cf",
            "cf industries",
            "cfg",
            "charles river laboratories",
            "charles schwab corporation",
            "charter communications",
            "chd",
            "chevron corporation",
            "chipotle mexican grill",
            "chrw",
            "chtr",
            "chubb limited",
            "church & dwight",
            "ci",
            "cigna",
            "cincinnati financial",
            "cinf",
            "cintas",
            "cisco",
            "citigroup",
            "citizens financial group",
            "cl",
            "clorox",
            "clx",
            "cmcsa",
            "cme",
            "cme group",
            "cmg",
            "cmi",
            "cms",
            "cms energy",
            "cnc",
            "cnp",
            "coca-cola company the",
            "cof",
            "cognizant",
            "coin",
            "coinbase",
            "colgate-palmolive",
            "comcast",
            "conagra brands",
            "conocophillips",
            "consolidated edison",
            "constellation brands",
            "constellation energy",
            "coo",
            "cooper companies the",
            "cop",
            "copart",
            "cor",
            "corning inc",
            "corpay",
            "corteva",
            "cost",
            "costar group",
            "costco",
            "coterra",
            "cpay",
            "cpb",
            "cprt",
            "cpt",
            "crl",
            "crm",
            "crowdstrike",
            "crwd",
            "csco",
            "csgp",
            "csx",
            "csx corporation",
            "ctas",
            "ctra",
            "ctsh",
            "ctva",
            "cummins",
            "cvs",
            "cvs health",
            "cvx",
            "czr",
            "d. r. horton",
            "dal",
            "danaher corporation",
            "darden restaurants",
            "dash",
            "datadog",
            "davita",
            "day",
            "dayforce",
            "dd",
            "ddog",
            "de",
            "deck",
            "deckers brands",
            "deere & company",
            "dell",
            "dell technologies",
            "delta air lines",
            "devon energy",
            "dexcom",
            "dg",
            "dgx",
            "dhi",
            "dhr",
            "diamondback energy",
            "digital realty",
            "dis",
            "dlr",
            "dltr",
            "doc",
            "dollar general",
            "dollar tree",
            "dominion energy",
            "domino's",
            "doordash",
            "dov",
            "dover corporation",
            "dow",
            "dow inc",
            "dpz",
            "dri",
            "dte",
            "dte energy",
            "duk",
            "duke energy",
            "dupont",
            "dva",
            "dvn",
            "dxcm",
            "ea",
            "eastman chemical company",
            "eaton corporation",
            "ebay",
            "ebay inc",
            "ecl",
            "ecolab",
            "ed",
            "edison international",
            "edwards lifesciences",
            "efx",
            "eg",
            "eix",
            "el",
            "electronic arts",
            "elevance health",
            "elv",
            "emerson electric",
            "emn",
            "emr",
            "enph",
            "enphase energy",
            "entergy",
            "eog",
            "eog resources",
            "epam",
            "epam systems",
            "eqix",
            "eqr",
            "eqt",
            "eqt corporation",
            "equifax",
            "equinix",
            "equity residential",
            "erie",
            "erie indemnity",
            "es",
            "ess",
            "essex property trust",
            "este lauder companies the",
            "etn",
            "etr",
            "everest group",
            "evergy",
            "eversource energy",
            "evrg",
            "ew",
            "exc",
            "exe",
            "exelon",
            "expand energy",
            "expd",
            "expe",
            "expedia group",
            "expeditors international",
            "exr",
            "extra space storage",
            "exxonmobil",
            "f inc",
            "factset",
            "fair isaac",
            "fang",
            "fast",
            "fastenal",
            "fcx",
            "fds",
            "fdx",
            "fe",
            "federal realty investment trust",
            "fedex",
            "ffiv",
            "fi",
            "fico",
            "fidelity national information services",
            "fifth third bancorp",
            "first solar",
            "firstenergy",
            "fis",
            "fiserv",
            "fitb",
            "ford motor company",
            "fortinet",
            "fortive",
            "fox",
            "fox corporation",
            "foxa",
            "franklin resources",
            "freeport-mcmoran",
            "frt",
            "fslr",
            "ftnt",
            "ftv",
            "garmin",
            "gartner",
            "gd",
            "gddy",
            "ge",
            "ge aerospace",
            "ge healthcare",
            "ge vernova",
            "gehc",
            "gen",
            "gen digital",
            "generac",
            "general dynamics",
            "general mills",
            "general motors",
            "genuine parts company",
            "gev",
            "gild",
            "gilead sciences",
            "gis",
            "gl",
            "global payments",
            "globe life",
            "glw",
            "gm",
            "gnrc",
            "godaddy",
            "goldman sachs",
            "goog",
            "googl",
            "gpc",
            "gpn",
            "grmn",
            "gs",
            "gww",
            "hal",
            "halliburton",
            "hartford the",
            "has",
            "hasbro",
            "hban",
            "hca",
            "hca healthcare",
            "hd",
            "healthpeak properties",
            "henry schein",
            "hershey company the",
            "hewlett packard enterprise",
            "hig",
            "hii",
            "hilton worldwide",
            "hlt",
            "hologic",
            "holx",
            "home depot the",
            "hon",
            "honeywell",
            "hormel foods",
            "host hotels & resorts",
            "howmet aerospace",
            "hp inc",
            "hpe",
            "hpq",
            "hrl",
            "hsic",
            "hst",
            "hsy",
            "hubb",
            "hubbell incorporated",
            "hum",
            "humana",
            "huntington bancshares",
            "huntington ingalls industries",
            "hwm",
            "ibkr",
            "ibm",
            "ice",
            "idex corporation",
            "idexx laboratories",
            "idxx",
            "iex",
            "iff",
            "illinois tool works",
            "incy",
            "incyte",
            "ingersoll rand",
            "intc",
            "intel",
            "interactive brokers",
            "intercontinental exchange",
            "international flavors & fragrances",
            "international paper",
            "interpublic group of companies the",
            "intu",
            "intuit",
            "intuitive surgical",
            "invesco",
            "invh",
            "invitation homes",
            "ip",
            "ipg",
            "iqv",
            "iqvia",
            "ir",
            "irm",
            "iron mountain",
            "isrg",
            "it",
            "itw",
            "ivz",
            "j.b. hunt",
            "j.m. smucker company the",
            "jabil",
            "jack henry & associates",
            "jacobs solutions",
            "jbht",
            "jbl",
            "jci",
            "jkhy",
            "jnj",
            "johnson & johnson",
            "johnson controls",
            "jpm",
            "jpmorgan chase",
            "kdp",
            "kellanova",
            "kenvue",
            "keurig dr pepper",
            "key",
            "keycorp",
            "keys",
            "keysight technologies",
            "khc",
            "kim",
            "kimberly-clark",
            "kimco realty",
            "kinder morgan",
            "kkr",
            "kkr & co",
            "kla corporation",
            "klac",
            "kmb",
            "kmi",
            "kmx",
            "ko",
            "kr",
            "kraft heinz",
            "kroger",
            "kvue",
            "labcorp",
            "lam research",
            "las vegas sands",
            "ldos",
            "leidos",
            "len",
            "lennar",
            "lennox international",
            "lh",
            "lharris",
            "lhx",
            "lii",
            "lilly eli",
            "lin",
            "linde plc",
            "live nation entertainment",
            "lkq",
            "lkq corporation",
            "lly",
            "lmt",
            "lockheed martin",
            "loews corporation",
            "low",
            "lowe's",
            "lrcx",
            "lulu",
            "lululemon athletica",
            "luv",
            "lvs",
            "lyb",
            "lyondellbasell",
            "lyv",
            "m&t bank",
            "ma",
            "maa",
            "mar",
            "marathon petroleum",
            "marketaxess",
            "marriott international",
            "marsh mclennan",
            "martin marietta materials",
            "mas",
            "masco",
            "mastercard",
            "match group",
            "mccormick & company",
            "mcd",
            "mcdonald's",
            "mchp",
            "mck",
            "mckesson corporation",
            "mco",
            "mdlz",
            "mdt",
            "medtronic",
            "merck & co",
            "met",
            "meta",
            "meta platforms",
            "metlife",
            "mettler toledo",
            "mgm",
            "mgm resorts",
            "mhk",
            "microchip technology",
            "micron technology",
            "microsoft",
            "mid-america apartment communities",
            "mkc",
            "mktx",
            "mlm",
            "mmc",
            "mmm",
            "mnst",
            "mo",
            "moderna",
            "moh",
            "mohawk industries",
            "molina healthcare",
            "molson coors beverage company",
            "mondelez international",
            "monolithic power systems",
            "monster beverage",
            "moody's corporation",
            "morgan stanley",
            "mos",
            "mosaic company the",
            "motorola solutions",
            "mpc",
            "mpwr",
            "mrk",
            "mrna",
            "ms",
            "msci",
            "msci inc",
            "msft",
            "msi",
            "mtb",
            "mtch",
            "mtd",
            "mu",
            "nasdaq inc",
            "nclh",
            "ndaq",
            "ndsn",
            "nee",
            "nem",
            "netapp",
            "netflix",
            "newmont",
            "news corp",
            "nextera energy",
            "nflx",
            "ni",
            "nike inc",
            "nisource",
            "nke",
            "noc",
            "nordson corporation",
            "norfolk southern",
            "northern trust",
            "northrop grumman",
            "norwegian cruise line holdings",
            "now",
            "nrg",
            "nrg energy",
            "nsc",
            "ntap",
            "ntrs",
            "nucor",
            "nue",
            "nvda",
            "nvidia",
            "nvr",
            "nvr inc",
            "nws",
            "nwsa",
            "nxp semiconductors",
            "nxpi",
            "occidental petroleum",
            "odfl",
            "oke",
            "old dominion",
            "omc",
            "omnicom group",
            "on",
            "on semiconductor",
            "oneok",
            "oracle corporation",
            "orcl",
            "oreilly automotive",
            "orly",
            "otis",
            "otis worldwide",
            "oxy",
            "paccar",
            "packaging corporation of america",
            "palantir technologies",
            "palo alto networks",
            "panw",
            "paramount skydance corporation",
            "parker hannifin",
            "payc",
            "paychex",
            "paycom",
            "paypal",
            "payx",
            "pcar",
            "pcg",
            "peg",
            "pentair",
            "pep",
            "pepsico",
            "pfe",
            "pfg",
            "pfizer",
            "pg",
            "pg&e corporation",
            "pgr",
            "ph",
            "philip morris international",
            "phillips",
            "phm",
            "pinnacle west capital",
            "pkg",
            "pld",
            "pltr",
            "pm",
            "pnc",
            "pnc financial services",
            "pnr",
            "pnw",
            "pool",
            "pool corporation",
            "ppg",
            "ppg industries",
            "principal financial group",
            "procter & gamble",
            "progressive corporation",
            "prologis",
            "pru",
            "prudential financial",
            "psa",
            "psky",
            "psx",
            "ptc",
            "ptc inc",
            "public service enterprise group",
            "public storage",
            "pultegroup",
            "pwr",
            "pypl",
            "qcom",
            "qualcomm",
            "quanta services",
            "quest diagnostics",
            "ralph lauren corporation",
            "raymond james financial",
            "rcl",
            "realty income",
            "reg",
            "regency centers",
            "regeneron pharmaceuticals",
            "regions financial corporation",
            "regn",
            "republic services",
            "resmed",
            "revvity",
            "rf",
            "rjf",
            "rl",
            "rmd",
            "rockwell automation",
            "rok",
            "rol",
            "rollins inc",
            "rop",
            "roper technologies",
            "ross stores",
            "rost",
            "royal caribbean group",
            "rsg",
            "rtx",
            "rtx corporation",
            "rvty",
            "s&p global",
            "salesforce",
            "sba communications",
            "sbac",
            "sbux",
            "schlumberger",
            "schw",
            "seagate technology",
            "sempra",
            "servicenow",
            "sherwin-williams",
            "shw",
            "simon property group",
            "sjm",
            "skyworks solutions",
            "slb",
            "smci",
            "smurfit westrock",
            "sna",
            "snap-on",
            "snps",
            "so",
            "solv",
            "solventum",
            "southern company",
            "southwest airlines",
            "spg",
            "spgi",
            "sre",
            "stanley black & decker",
            "starbucks",
            "state street corporation",
            "ste",
            "steel dynamics",
            "steris",
            "stld",
            "stryker corporation",
            "stt",
            "stx",
            "stz",
            "supermicro",
            "sw",
            "swk",
            "swks",
            "syf",
            "syk",
            "synchrony financial",
            "synopsys",
            "sysco",
            "syy",
            "t-mobile us",
            "t. rowe price",
            "take-two interactive",
            "tap",
            "tapestry inc",
            "targa resources",
            "target corporation",
            "tdg",
            "tdy",
            "te connectivity",
            "tech",
            "tel",
            "teledyne technologies",
            "ter",
            "teradyne",
            "tesla inc",
            "texas instruments",
            "texas pacific land corporation",
            "textron",
            "tfc",
            "tgt",
            "thermo fisher scientific",
            "tjx",
            "tjx companies",
            "tko",
            "tko group holdings",
            "tmo",
            "tmus",
            "tpl",
            "tpr",
            "tractor supply",
            "trade desk the",
            "trane technologies",
            "transdigm group",
            "travelers companies the",
            "trgp",
            "trimble inc",
            "trmb",
            "trow",
            "truist financial",
            "trv",
            "tsco",
            "tsla",
            "tsn",
            "tt",
            "ttd",
            "ttwo",
            "txn",
            "txt",
            "tyl",
            "tyler technologies",
            "tyson foods",
            "u.s. bancorp",
            "ual",
            "uber",
            "udr",
            "udr inc",
            "uhs",
            "ulta",
            "ulta beauty",
            "unh",
            "union pacific corporation",
            "united airlines holdings",
            "united parcel service",
            "united rentals",
            "unitedhealth group",
            "universal health services",
            "unp",
            "ups",
            "uri",
            "usb",
            "valero energy",
            "ventas",
            "veralto",
            "verisign",
            "verisk analytics",
            "verizon",
            "vertex pharmaceuticals",
            "viatris",
            "vici",
            "vici properties",
            "visa inc",
            "vistra corp",
            "vlo",
            "vlto",
            "vmc",
            "vrsk",
            "vrsn",
            "vrtx",
            "vst",
            "vtr",
            "vtrs",
            "vulcan materials company",
            "vz",
            "w. r. berkley corporation",
            "w. w. grainger",
            "wab",
            "wabtec",
            "walmart",
            "walt disney company the",
            "warner bros. discovery",
            "waste management",
            "wat",
            "waters corporation",
            "wbd",
            "wday",
            "wdc",
            "wec",
            "wec energy group",
            "well",
            "wells fargo",
            "welltower",
            "west pharmaceutical services",
            "western digital",
            "weyerhaeuser",
            "wfc",
            "williams companies",
            "williams-sonoma inc",
            "willis towers watson",
            "wm",
            "wmb",
            "wmt",
            "workday inc",
            "wrb",
            "wsm",
            "wst",
            "wtw",
            "wy",
            "wynn",
            "wynn resorts",
            "xcel energy",
            "xel",
            "xom",
            "xyl",
            "xylem inc",
            "xyz",
            "yum",
            "yum brands",
            "zbh",
            "zbra",
            "zebra technologies",
            "zimmer biomet",
            "zoetis",
            "zts",
        ],
        "keywords": ["regulation", "policy", "statement", "privacy", "data"],
    },
    "reranking": {
        "enabled": True,
        "model": "all-mpnet-base-v2",
        "threshold": 0.1,
        "seed_quotes": [
            "The company stated that",
            "According to the CEO",
            "We are committed to",
        ],
    },
}
