# Ultimate comprehensive corpus-extractors configuration with maximum coverage
# Combines best elements from all config files for optimal quote extraction
# Enhanced for maximum coverage and minimal noise

config = {
    "nlp": {
        "spacy_model": "en_core_web_sm",
        "fallback_model": "en_core_web_sm",
        "use_gpu": False,
        "enable_ner": True,
        "role_keywords": [
            "board member",
            "board member and president officer",
            "board_member",
            "ceo",
            "cfo",
            "chair",
            "chairman",
            "chairwoman",
            "chief compliance officer",
            "chief executive officer",
            "chief financial & accounting officer) [ 4 ]",
            "chief financial officer",
            "chief financial officer chief operating officer",
            "chief human resources officer",
            "chief information officer",
            "chief innovation officer",
            "chief legal officer",
            "chief marketing officer",
            "chief operating officer",
            "chief risk officer",
            "chief scientist",
            "chief strategy officer",
            "chief technology officer",
            "co-chief operating officer",
            "co-founder",
            "co-president officer",
            "colgate",
            "coo",
            "corporation",
            "cpo",
            "cto",
            "dennison manufacturing company",
            "director",
            "executive",
            "executive_chairman",
            "founder",
            "general counsel",
            "head of private equity",
            "lead independent board member",
            "manager",
            "managing director",
            "officer",
            "partner",
            "president",
            "president officer",
            "principal",
            "representative",
            "secretary",
            "spokesperson",
            "treasurer",
            "vice president",
            "vp",
            # Additional titles from enhanced config for maximum coverage
            "spokesperson",
            "representative",
            "Chairman",
            "Chairwoman",
            "Chair",
            "Chief Executive Officer",
            "Chief Financial Officer",
            "Chief Operating Officer",
            "Chief Technology Officer",
            "Executive",
            "Board Member",
            "General Counsel",
        ],
        "executive_names": [
            "Aaron Jagdfeld",
            "Aaron Lufkin Dennison",
            "Aart de Geus",
            "Abhi Khandelwal",
            "Abhi Talwalkar",
            "Adaire Fox-Martin",
            "Adaire Fox-martin",
            "Adam H. Schechter",
            "Adam Rymer",
            "Adam Satterfield",
            "Addison Rand",
            "Adena Friedman",
            "Advance Publications",
            "Ahmad Bahai",
            "Ajit Jain",
            "Al Avery",
            "Alan B. Miller",
            "Alan Campbell",
            "Alan D. Schnitzer",
            "Alan G. Hassenfeld",
            "Alan S. Armstrong",
            "Alan Shugart",
            "Albert Bourla",
            "Albert G. White",
            "Albert G. White III",
            "Albert J. Neupaver",
            "Aldo J. Pagliari",
            "Alesia Haas",
            "Alex Chriss",
            "Alex Darbeloff",
            "Alex Karp",
            "Alex Manoogian",
            "Alex d'Arbeloff",
            "Alexander J. Jessett",
            "Alexis Lê-Quôc",
            "Alexis Lê-quôc",
            "Alfred P. Sloan CEO",
            "Alfred P. Sloan Ceo",
            "Alice Marriott",
            "Allen J. Mistysyn",
            "Allen Rosenshine",
            "Allison Niderno",
            "Alok Maskara",
            "Alonzo G. Decker",
            "Altaf Rupani",
            "Alva Kinney",
            "Alvin B. Phillips",
            "Amory Houghton",
            "Amrita Ahuja",
            "Amy Woods Brinkley",
            "Anat Ashkenazi",
            "And Ceo",
            "And Chairman",
            "And J.r. Ridgway",
            "And President",
            "Anders Gustafsson",
            "Andre Maciel",
            "Andrea Albertini",
            "Andrea J. Ayers",
            "Andres Gluski",
            "Andrew Anagnost",
            "Andrew Bosworth",
            "Andrew C. Florance",
            "Andrew Cecere",
            "Andrew Dennison",
            "Andrew Dickinson",
            "Andrew Florance",
            "Andrew Hider",
            "Andrew McCollum",
            "Andrew Mccollum",
            "Andrew P. Power",
            "Andrew Schlossberg",
            "Andrew Silvernail",
            "Andrew Viterbi",
            "Andrew Wiechmann",
            "Andrew Wilson",
            "Andrew Young",
            "Andrew “Drew” Marsh",
            "Andrew “drew” Marsh",
            "André Calantzopoulos",
            "Andréa Carter",
            "Andy Bechtolsheim",
            "Andy Fang",
            "Andy Jassy",
            "Andy Saperstein",
            "Andy Sullivan",
            "Aneel Bhusri",
            "Angela L. Kleiman",
            "Angela L. Kleiman,",
            "Anirudh Devgan",
            "Annette F. Favorite",
            "Anthony Capuano",
            "Anthony Carano",
            "Anthony Smurfit",
            "Antonio Neri",
            "April Arnzen",
            "Archibald Taft",
            "Ari Bousbib",
            "Ari Emanuel",
            "Ariane Gorin",
            "Armando Pimentel",
            "Armando Pimentel Jr.",
            "Arne Wilhelmsen",
            "Arnold Rosen",
            "Arthur Blank",
            "Arthur J. Gallagher",
            "Arthur J. Schmitt",
            "Arthur L. Parker",
            "Arthur Levinson",
            "Arthur Rock",
            "Arvind Krishna",
            "Asa Griggs Candler",
            "Aubrey McClendon",
            "Aubrey Mcclendon",
            "Austin Church",
            "B. Thomas Golisano",
            "B. Wayne Hughes",
            "Badri Kothandaraman",
            "Baer Pettit",
            "Balazs Fejes",
            "Bank Of America",
            "Bank of America",
            "Barry Babcock",
            "Barry Diller",
            "Ben Tisch",
            "Benjamin G. Clark",
            "Benjamin Holt",
            "Benjamin Newton Duke",
            "Benjamin Schall",
            "Berkshire Hathaway",
            "Bernard Cammarata",
            "Bernard J. Birkett",
            "Bernard J. Zovighian",
            "Bernard Kroger",
            "Bernard Marcus",
            "Beth A. Costello",
            "Beth Whited",
            "Bill Amos",
            "Bill Bowerman",
            "Bill Dally",
            "Bill Fair",
            "Bill Fehrman",
            "Bill Gates",
            "Bill Grogan",
            "Bill Hornbuckle",
            "Bill Isackson",
            "Bill Krieger",
            "Bill McDermott",
            "Bill Mcdermott",
            "Bill Nash",
            "Bill Newlands",
            "Bill Seidemann",
            "Bill W. Wheat",
            "Billy Gifford",
            "BlackRock",
            "Blackrock",
            "Blake Moret",
            "Bob Fishman",
            "Bob Foster",
            "Bob Iger",
            "Bob Jordan",
            "Bob Kierlin",
            "Bob Miner",
            "Bob Parsons",
            "Bob Pragada",
            "Bob Sulentic",
            "Bow Ruggeri",
            "Brad Beckham",
            "Brad Greiwe",
            "Brad Jacobs",
            "Brad Smith",
            "Brad Trenkle",
            "Bradley S. Powell",
            "Brandon Sink",
            "Brendan Foley",
            "Brett Hart",
            "Brett Sandercock",
            "Brian Armstrong",
            "Brian Chesky",
            "Brian Cornell",
            "Brian D. Savoy",
            "Brian DelGhiaccio",
            "Brian Delghiaccio",
            "Brian Doubles",
            "Brian Evanko",
            "Brian J. Van Abel",
            "Brian J. van Abel",
            "Brian L. Roberts",
            "Brian Moynihan",
            "Brian Niccol",
            "Brian S. Tyler",
            "Brian Sharples",
            "Brian X. Tierney",
            "Bruce Bodine",
            "Bruce Hansen",
            "Bruce Thompson",
            "Bruce Van Saun",
            "Bruce van Saun",
            "Bryan D. Preston",
            "Bryan Hanson",
            "Bud Walton",
            "Burdett J. Johnson",
            "Byron L. Smith",
            "Byron Laflin Smith",
            "Börje Ekholm",
            "C. David Molina",
            "C. Nye",
            "C.B. Ames",
            "C.E. Woolman",
            "C.L. Best",
            "C.b. Ames",
            "C.e. Woolman",
            "C.l. Best",
            "Cadwallader C. Washburn",
            "Cal Turner",
            "Caleb Bradham",
            "Calvin Butler",
            "Calvin McDonald",
            "Calvin Mcdonald",
            "Cam Weber",
            "Cameron M. Bready",
            "Campbell P. Brown",
            "Capital Research Global Investors",
            "Carl Eschenbach",
            "Carl Hess",
            "Carl von Linde",
            "Carlos Abrams-Rivera",
            "Carlos Abrams-rivera",
            "Carlos M. Hernandez",
            "Carlyle And",
            "Carlyle and",
            "Carol B. Tomé",
            "Carol Meyrowitz",
            "Caroline Dorsa",
            "Caroline Litchfield",
            "Carolyn Burke",
            "Carter H. Andrus",
            "Cator Woolford",
            "Cecil H. Green",
            "Cedric W. Burgher",
            "Cedric W. Burgher, CFO",
            "Celeste Burgoyne",
            "Chad Richison",
            "Chair",
            "Chairman Of The Board",
            "Chairperson",
            "Charles Arnao",
            "Charles B. Clark",
            "Charles D. McCrary",
            "Charles D. Mccrary",
            "Charles F. Erhart",
            "Charles F. O'Reilly",
            "Charles F. Oreilly",
            "Charles G. Smith",
            "Charles Geschke",
            "Charles H. O'Reilly",
            "Charles H. Oreilly",
            "Charles Henry Robinson",
            "Charles Husband",
            "Charles Jeremiah Smith",
            "Charles K Vaughan",
            "Charles Kettering Director Of Research",
            "Charles Kettering Director of Research",
            "Charles Liang",
            "Charles M. Olcott",
            "Charles N. Felton",
            "Charles Pfizer",
            "Charles R. Schwab",
            "Charles Ranlett Flint",
            "Charles Scharf",
            "Charles Schmidt",
            "Charles Simmons",
            "Charles Snyder",
            "Charles Trimble Et Al.",
            "Charles Trimble et al.",
            "Charles W. Brady",
            "Charles Weissmann",
            "Cheryl Norton",
            "Cheryl Norton, EVP and Chief Operating Officer",
            "Chicago Board Of Trade",
            "Chicago Board of Trade",
            "Chief Financial Officer",
            "Chip Bergh",
            "Chip Wilson",
            "Chris Boerner",
            "Chris Cocks",
            "Chris Concannon",
            "Chris Cox",
            "Chris Gorman",
            "Chris Hughes",
            "Chris Isaacson",
            "Chris Kempczinski",
            "Chris Kubasik",
            "Chris Malachowsky",
            "Chris Perry",
            "Chris Steddum",
            "Chris Suh",
            "Chris Viehbacher",
            "Chris Winfrey",
            "Chris Womack",
            "Christine Leahy",
            "Christophe Beck",
            "Christophe Le Caillec",
            "Christophe le Caillec",
            "Christopher A. O'Herlihy",
            "Christopher A. Oherlihy",
            "Christopher D. Kastner",
            "Christopher DelOrefice",
            "Christopher Delorefice",
            "Christopher J. Nassetta",
            "Christopher J. Swift",
            "Christopher Payne",
            "Christopher T. Calio",
            "Chro",
            "Chuck Magro",
            "Chuck Robbins",
            "Clark Khayat",
            "Clay Gaspar",
            "Clay Holder",
            "Clessie Lyle Cummins",
            "Cliff Pemble",
            "Collis Potter Huntington",
            "Congdon Family",
            "Congdon family",
            "Conor C. Flynn",
            "Conrad Hilton",
            "Conrad Schlumberger",
            "Corie Barry",
            "Cornelius Vander Starr",
            "Craig Arnold",
            "Craig Barratt",
            "Craig Billings",
            "Craig Donohue",
            "Craig Safian",
            "Crawford W. Beveridge",
            "Cristiano Amon",
            "Curtis Priem",
            "Cynthia T. Jamison",
            "César Cernuda",
            "D. Keith Oden",
            "D.G. Macpherson",
            "D.g. Macpherson",
            "Dallas B. Tanner",
            "Dan Amos",
            "Dan Drake",
            "Dan Fisher",
            "Dan Letter",
            "Dan Simkowitz",
            "Daniel",
            "Daniel A. Carestio",
            "Daniel Cregg",
            "Daniel E. Pinto",
            "Daniel Guglielmone",
            "Daniel Hesse",
            "Daniel L. Florness",
            "Daniel Lewin",
            "Daniel O'Day",
            "Daniel Oday",
            "Daniel Tucker",
            "Dara Khosrowshahi",
            "Darius Adamczyk",
            "Darren Woods",
            "Daryl N. Bible",
            "Daryl Simm",
            "Dave Duffield",
            "Dave Gitlin",
            "Dave Lennox",
            "Dave Moellenhoff",
            "Dave Mosley",
            "Dave Pickles",
            "Dave Regnery",
            "Dave Rosa",
            "David A. Brandon",
            "David A. Jones",
            "David A. Jones Sr.",
            "David A. Montecalvo",
            "David A. Ricks",
            "David A. Zapico",
            "David Altshuler",
            "David Blitzer",
            "David Bowler",
            "David Bowler, EVP and Chief Financial Officer",
            "David Bozeman",
            "David Campbell",
            "David Cheriton",
            "David Coors",
            "David Cordani",
            "David E. Simon",
            "David Elkins",
            "David Ellison",
            "David Evans Shaw",
            "David Faeder",
            "David G. Barnes",
            "David Gansberg",
            "David Gibbs",
            "David Gregory",
            "David Hitz",
            "David Howson",
            "David J. Neithercut",
            "David J. Turner",
            "David J. Turner, Jr.",
            "David Joyner",
            "David K. Lam",
            "David Kenny",
            "David Lauren",
            "David Loo",
            "David M. Solomon",
            "David Marriott",
            "David Ossip",
            "David Rudd",
            "David Rumph",
            "David S. Congdon",
            "David Taylor",
            "David V. Auld",
            "David Weigand",
            "David Williams",
            "David Zaslav",
            "David Zinsner",
            "Dean Buntrock",
            "Deanna Strable",
            "Deborah Weitzman",
            "Debra Cafaro",
            "Dee Hock",
            "Deidra Merriwether",
            "Dennis Bakke",
            "Dennis Gillings",
            "Dennis Wilson",
            "Denson N. Franklin III,",
            "Denson N. Franklin Iii",
            "Deon Stander",
            "Dermot McDonogh",
            "Dermot Mcdonogh",
            "Derrick Rossi",
            "Devin Stockfish",
            "Diane Cafritz",
            "Dick George",
            "Dinos Iordanou",
            "Dirk Van de Put",
            "Dirk van de Put",
            "Dmitri Alperovitch",
            "Domenic J. Dell'Osso, Jr.",
            "Domenic J. Dellosso",
            "Dominick Burke",
            "Dominick DeVarti",
            "Dominick Devarti",
            "Don Allan",
            "Don Clegg",
            "Don Goodliffe",
            "Donald Baxter",
            "Donald C. Wood",
            "Donald F. Flynn",
            "Donald Knauss",
            "Donald Ray Horton",
            "Donnie King",
            "Doug Abbey",
            "Doug Brooks",
            "Doug Mahon",
            "Doug McMillon",
            "Doug Mcmillon",
            "Doug Otto",
            "Doug Pitman",
            "Douglas Dayton And John Geisse",
            "Douglas Dayton and John Geisse",
            "Douglas T. Linde",
            "Douglas W. Peacock",
            "Dustin Moskovitz",
            "Dwight Schar",
            "E. R. Squibb",
            "E. Scott Santi",
            "Earl C. Austin",
            "Earl C. Austin Jr.",
            "Earl Congdon",
            "Earl Congdon Sr.",
            "Earl Isaac",
            "Ed Bastian",
            "Ed Hill",
            "Ed Ho",
            "Ed Kaplan",
            "Ed Oates",
            "Eduardo F. Menezes",
            "Eduardo Saverin",
            "Edward B. Pitoniak",
            "Edward D. Breen",
            "Edward E. Rieck",
            "Edward H. Linde",
            "Edward Hughes",
            "Edward Mead Johnson",
            "Edward Philip",
            "Edward Temple",
            "Edward Williams",
            "Edwin Roks",
            "Elaine Wynn",
            "Eli Lilly",
            "Elisha Otis",
            "Elizabeth \"Betty\" Brinn",
            "Elizabeth Betty Brinn",
            "Elizabeth E. Tallett",
            "Elliott Hill",
            "Elon Musk",
            "Emeritus",
            "Emilie Choi",
            "Enrique Lores",
            "Enrique Mayor-Mora",
            "Enrique Mayor-mora",
            "Erhard Mettler",
            "Erhard Mettler And Henry Theobald",
            "Eric Andersen",
            "Eric Ashleman",
            "Eric Chewning",
            "Eric M. Green",
            "Eric Pierson Swenson",
            "Eric Pierson Swenson, et al",
            "Eric Resnick",
            "Eric Zinterhofer",
            "Erik Fyrwald",
            "Erle P. Halliburton",
            "Ernie Herrman",
            "Ester Banque",
            "Estée Lauder",
            "Eugene Bredow",
            "Eugene L. Batchelder",
            "Eugene L. Batchelder, Chairman",
            "Eugene McDermott",
            "Eugene Mcdermott",
            "Evan G. Greenberg",
            "Evan Moore",
            "Evan Scott",
            "Evelyn J. Clark",
            "Ezra Y. Yacob",
            "F. Thomson Leighton",
            "Fairleigh S. Dickinson",
            "Finis Conner",
            "Flemming Ørnskov",
            "Frank D. Yeary",
            "Frank Dominguez",
            "Frank E. Dangeard",
            "Frank M. Svoboda",
            "Frank Phillips",
            "Frank Simuro",
            "Frank St. John",
            "Frank St. Romain",
            "Franklin Antonio",
            "François Locoh-Donou",
            "François Locoh-donou",
            "François Morin",
            "Fred Ehrsam",
            "Fred Luddy",
            "Fred Rothman",
            "Frederick Rentschler",
            "Frederick Trent Stanley",
            "Frederick W. Smith",
            "Friedrich Weyerhäuser",
            "Gail Koziara Boudreaux",
            "Gale Klappa",
            "Gale Klappa, Executive Chairman, Scott Lauber, CEO",
            "Garrett Camp",
            "Garrick Rochow",
            "Gary Burrell",
            "Gary Carano",
            "Gary Cohn",
            "Gary E. Dickerson",
            "Gary Hendrix",
            "Gary Rollins",
            "Gary S. Guthart",
            "Gary Swidler",
            "Gavin Hattersley",
            "Gene Hall",
            "Geoff Martha",
            "Geoff Molson",
            "George A. Archer",
            "George A. Hormel",
            "George E. Cates",
            "George Eastman",
            "George Garvin Brown",
            "George Kao",
            "George Kozmetsky",
            "George Kurian",
            "George Kurtz",
            "George L. Miller",
            "George M. Marcus",
            "George Markus Loturco",
            "George Merck",
            "George R. Roberts",
            "George Winthrop Fairchild",
            "George Yancopoulos",
            "Gerben Bakker",
            "Gerhard Cless",
            "Gideon Gartner",
            "Glen Hauenstein",
            "Glenn D. Fogel",
            "Glenn G. Cohen",
            "Glenn Hubbard",
            "Global Clinical",
            "Gordon Bowker",
            "Gordon Gund",
            "Gordon Moore",
            "Governed By A 14-member Board Of Trustees. Sanford Cloud",
            "Governed by a 14-member Board of Trustees.  Sanford Cloud, Jr., Lead Trustee",
            "Greg Abel",
            "Greg Brown",
            "Greg Case",
            "Greg Heckman",
            "Greg Maffei",
            "Greg Penner",
            "Greg Peters",
            "Gregg Brummer",
            "Gregg Marston",
            "Gregory E. Johnson",
            "Gregory Ebel",
            "Gregory H. Boyce",
            "Gregory Hebard",
            "Gregory J. Hayes",
            "Gregory Plemmons",
            "Gunjan Kedia",
            "Gus Blanchard",
            "Guy Woolford",
            "H Lynn Moore Jr.",
            "H Lynn Moore Jr.,",
            "H. Edward Hanway",
            "H. Eric Bolton",
            "H. Eric Bolton, Jr.",
            "H. Lawrence Culp",
            "H. Lawrence Culp Jr.",
            "H.M. Byllesby",
            "H.m. Byllesby",
            "Hal Lawton",
            "Hamid Moghadam",
            "Hamilton E. James",
            "Hans Vestberg",
            "Harold Stanley",
            "Harris Fricker",
            "Harry Rosenthal",
            "Harry Sideris",
            "Harry Sommer",
            "Harvey Hubbell",
            "Hassane El-Khoury",
            "Hassane El-khoury",
            "Havilah Babcock",
            "Haviv Ilan",
            "Heath Monesmith",
            "Heidi G. Petz",
            "Heinz Schaller",
            "Helen L. Shan CFO , Executive Vice President",
            "Helen L. Shan Cfo",
            "Henry A. Fernandez",
            "Henry Ford",
            "Henry Hassenfeld",
            "Henry Kravis",
            "Henry Orth Hirt",
            "Henry R. Kravis",
            "Henry S. Bryan",
            "Henry Samueli",
            "Henry Schein",
            "Henry Sherwin",
            "Henry Singleton",
            "Henry Sturgis Morgan",
            "Henry Taub",
            "Henry Wells",
            "Henry Willis",
            "Herb Kelleher",
            "Herbert Henry Dow",
            "Herbert Irving",
            "Herbert Simon",
            "Herman Hassenfeld",
            "Herman Hollerith",
            "Hermon W. Cable",
            "Hervé Hoppenot",
            "Hillel Hassenfeld",
            "Hilton Schlosberg",
            "Hock Tan",
            "Holden Lewis",
            "Homer Stryker",
            "Howard Schultz",
            "Howard Wille",
            "Howard Wood",
            "Howard Y. Chang",
            "Hubert Hansen",
            "Hugh J. Chisholm",
            "Inga Beale",
            "Irving Tan",
            "Irwin Jacobs",
            "Isabella Pirzadeh",
            "Itero Scanner And Services Business",
            "Ivan Tornos",
            "J. Danley Budd",
            "J. Eric Bjornholt",
            "J. Erik Jonsson",
            "J. Hyatt Brown",
            "J. Kevin Akers",
            "J. Larry Nichols",
            "J. Patrick Gallagher",
            "J. Patrick Gallagher, Jr.",
            "J. Powell Brown",
            "J. Robert \"Bob\" Beyster",
            "J. Robert Bob Beyster",
            "J. Thomas Hill",
            "J. Willard Marriott",
            "Jacek Olczak",
            "Jack C. Massey",
            "Jack Dorsey",
            "Jack Dorsey Chair",
            "Jack Henry",
            "Jack Henry & Jerry Hall",
            "Jamere Jackson",
            "James Bidzos",
            "James Buchanan Duke",
            "James C. Fish",
            "James C. Fish, Jr.",
            "James C. Foster",
            "James Conroy",
            "James E. Casey",
            "James F. Risoleo",
            "James Ford Bell",
            "James Gamble",
            "James Golden",
            "James H. McGraw",
            "James H. Mcgraw",
            "James Hackett",
            "James Hippel",
            "James L. Ossowski",
            "James L. Ossowski,",
            "James Lau",
            "James Logan Waters",
            "James Luther Turner",
            "James M. Cracchiolo",
            "James P. Gorman",
            "James R. Chapman",
            "James S. Kuhn",
            "James Sinegal",
            "James Snee",
            "James Solomon",
            "James Taiclet",
            "James Tisch",
            "James Wheeler",
            "James Wood Johnson",
            "Jamey Mock",
            "Jamie Caulfield",
            "Jamie Dimon",
            "Jamie Iannone",
            "Jane Fraser",
            "Janice Chaffin",
            "Jason Hollar",
            "Jason Liberty",
            "Jason P. Wells",
            "Jason S. Armstrong",
            "Jasper Rand",
            "Jasper Rand, Jr.",
            "Javier J. Rodriguez",
            "Javier Olivan",
            "Jay A. Stein",
            "Jay A. Stein Chairman-emeritus",
            "Jay Adair",
            "Jay Adelson",
            "Jay Mazelsky",
            "Jay Morse",
            "Jay S. Walker",
            "Jayshree Ullal",
            "Jeff Bezos",
            "Jeff Clarke",
            "Jeff Green",
            "Jeff Henley",
            "Jeff Howie",
            "Jeff Liaw",
            "Jeff Miller",
            "Jeff Noddle",
            "Jeff Shell",
            "Jeff Tate",
            "Jeffrey A. Goldstein",
            "Jeffrey A. Stoops",
            "Jeffrey B. Guldner",
            "Jeffrey Brotman",
            "Jeffrey Edwards",
            "Jeffrey Edwards, Director",
            "Jeffrey Harmening",
            "Jeffrey Kaplan",
            "Jeffrey L. Ritenour",
            "Jeffrey Leiden",
            "Jeffrey Lorberbaum",
            "Jeffrey Sprecher",
            "Jeffrey W. Martin",
            "Jennifer A. Parmentier",
            "Jennifer M. Johnson",
            "Jennifer Piepszak",
            "Jennifer Rumsey",
            "Jensen Huang",
            "Jerald Kent",
            "Jeremy Knop",
            "Jerome Kohlberg",
            "Jerome Kohlberg Jr.",
            "Jerome Monroe Smucker",
            "Jerry Baldwin",
            "Jerry E. Gahlhoff",
            "Jerry E. Gahlhoff, Jr.",
            "Jerry M. Sudarsky",
            "Jerry Sanders",
            "Jill Griebenow",
            "Jim Burke",
            "Jim Davis",
            "Jim Farley",
            "Jim Fitterling",
            "Jim Lyski",
            "Jim McKelvey",
            "Jim Mckelvey",
            "Jim Monaghan",
            "Jim Nickolas",
            "Jim Rechtin",
            "Jim Turley",
            "Jim Umpleby",
            "Jim Vena",
            "Jim Williamson",
            "Jim Zelter",
            "Joakim Weidemanis",
            "Joanne Crevoiserat",
            "Joaquin Duato",
            "Jodee Kozlak",
            "Joe Creed",
            "Joe Gebbia",
            "Joe Hogan",
            "Joe Lonsdale",
            "Joe Parkinson",
            "Joel Grade",
            "Joel S. Marcus",
            "Johann P. G. Bunge",
            "John A. Hill",
            "John A. Kimberly",
            "John Abele",
            "John Amos",
            "John Ayala",
            "John Baptiste Ford",
            "John Bernbach",
            "John C. Dugan",
            "John C. Griffith",
            "John C. Griffith, President and Chief Executive Officer",
            "John C. Malone",
            "John C. May",
            "John C. Plant",
            "John C. Plant ,",
            "John Crosby",
            "John D. Wren",
            "John Deere",
            "John Donahoe",
            "John Dwan",
            "John Dwight",
            "John E. Stokely",
            "John E. Stokely,",
            "John F. Baugh",
            "John F. Dryden",
            "John F. Lundgren",
            "John F. Morici",
            "John F. Wilson",
            "John G. Morikis",
            "John Gibson",
            "John H. Tyson",
            "John Hoke",
            "John Hoke III",
            "John J. Christmann IV",
            "John J. Christmann Iv",
            "John J. Schiff",
            "John J. Schiff Sr.",
            "John J. Zillmer",
            "John Klinger",
            "John Kuhlow",
            "John L. Hennessy",
            "John L. Stauch",
            "John M. Pasquesi",
            "John M. Turner",
            "John M. Turner, Jr.",
            "John McKesson",
            "John Mckesson",
            "John Moody",
            "John Murphy",
            "John N. Roberts",
            "John N. Roberts, III",
            "John Nichols",
            "John Olin",
            "John Olin Executive Vice President And Cfo",
            "John P. Nallen",
            "John P. Surma",
            "John Philip Holland",
            "John Pitcairn",
            "John Pitcairn Jr.",
            "John Q. Doyle",
            "John Reay",
            "John Reay Ceo",
            "John Rex",
            "John Ripley Myers",
            "John S. Marr Jr.",
            "John S. Marr Jr.,",
            "John Stankey",
            "John Stone",
            "John T. Cahill",
            "John Tappan",
            "John Towers",
            "John W. Daniels",
            "John W. Emerson",
            "John W. Gamble",
            "John W. Gamble, Jr.",
            "John W. Garratt",
            "John W. Ketchum",
            "John W. Ketchum Chairman",
            "John W. Rollins",
            "John W. Stanton",
            "John W. Tyson",
            "John Walker",
            "John Warnock",
            "John Zito",
            "Johnelle Hunt",
            "Johnnie Bryan Hunt",
            "Joi Harris",
            "Jon Jaffe",
            "Jon Monson",
            "Jon R. Moeller",
            "Jon Vander Ark",
            "Jonathan D. Gray",
            "Jonathan Gray",
            "Jonathan Pong",
            "Jonathan Pong,",
            "Jonathan Seelig",
            "Joseph A. Campbell",
            "Joseph Bae",
            "Joseph Baratta",
            "Joseph D. Fisher",
            "Joseph D. Margolis",
            "Joseph D. Russell",
            "Joseph D. Russell, Jr.",
            "Joseph Dominguez",
            "Joseph F. McKinney",
            "Joseph F. Mckinney",
            "Joseph Forline",
            "Joseph J. Jacobs",
            "Joseph Johnson",
            "Joseph Lauder",
            "Joseph Oriel Eaton",
            "Joseph Oriel Eaton II",
            "Joseph R. Hinrichs",
            "Joseph R. Nolan",
            "Joseph V. Taranto",
            "Joseph Zubretsky",
            "Josh Harris",
            "Joshua Isner",
            "Joshua Weinstein",
            "Juan Luciano",
            "Judy Marks",
            "Julia L. Johnson",
            "Julia L. Johnson, Director",
            "Julie Edwards",
            "Julie Sweet",
            "Justin Jude",
            "Justin Leong",
            "Justin O. Zimmer",
            "K. Gunnar Bjorklund",
            "Kaes Van't Hof",
            "Kaes Vant Hof",
            "Karen L. Parkhill",
            "Karim Boussebaa",
            "Karl F. Kurz",
            "Karl F. Kurz, Board member",
            "Karl F. Lopker",
            "Karl Slatoff",
            "Karleen Marie Oberton",
            "Kathleen L. Quirk",
            "Kathy J. Warden",
            "Katrin Pucknat",
            "Kazuo Okada",
            "Kecia Steelman",
            "Keith J. Allman",
            "Keith Jensen",
            "Keith W. Demmings",
            "Kelly Mahon Tullier",
            "Kelly Ortberg",
            "Kelsey Wirth",
            "Kelvin O. Moses",
            "Ken Howery",
            "Ken Langone",
            "Ken Xie",
            "Kenneth Duda",
            "Kenneth Murray",
            "Kenneth R. Chien",
            "Kenneth Volk",
            "Kenneth Volk Jr.",
            "Kenneth Woolley",
            "Kent Masters",
            "Kevin \"Marty\" Freeman",
            "Kevin A. Lobo",
            "Kevin Hourican",
            "Kevin J. Pearson",
            "Kevin J. Wheeler",
            "Kevin Marty Freeman",
            "Kevin P. Clark",
            "Kevin P. O’Shea",
            "Kevin P. O’shea",
            "Kevin Sayer",
            "Kevin Stein",
            "Kim Kelderman",
            "Kim R Cocklin",
            "Kimberly A. Dang",
            "Kimberly J. Harris",
            "Kimberly J. Harris, Director",
            "Kirk Kerkorian",
            "Kirk Perry",
            "Kirkland H. Donald",
            "Koh Boon Hwee",
            "Kristin Peck",
            "Kumar Mahadeva",
            "Kurt J. Hilzinger",
            "Kurt Sievers",
            "L.E. Phillips",
            "L.e. Phillips",
            "Lachlan Murdoch",
            "Lainie Goldstein",
            "Lal Karsanbhai",
            "Lane Riggs",
            "Larry Coben",
            "Larry Ellison",
            "Larry Fink",
            "Larry Merlo",
            "Larry Page",
            "Later",
            "Laura Alber",
            "Laura Miele",
            "Lauren Peters",
            "Laurence K. Marshall",
            "Laurie P. Havanec",
            "Laurie P. Havanec, Director",
            "Lavanya Chandrashekar",
            "Lawrence D. McRae",
            "Lawrence D. Mcrae",
            "Lawrence Kingsley",
            "Lawson E. Whiting",
            "Lawton W. Fitt",
            "Lee Raymond",
            "Lee Shavel",
            "Leon Black",
            "Leon Topalian",
            "Leonard \"Lenny\" Singh",
            "Leonard Bosack",
            "Leonard Lenny Singh",
            "Leonard Miller",
            "Leonard P. Pool",
            "Leonard Schleifer",
            "Lester Knight",
            "Liberty Media",
            "Lillian Congdon",
            "Linda Filler",
            "Linda Filler Jennifer L. Honeycutt",
            "Linda Rendle",
            "Lip-Bu Tan",
            "Lip-bu Tan",
            "Lisa Palmer",
            "Lisa Ruggles",
            "Lisa Su",
            "Lloyd Tevis",
            "Lloyd Yates",
            "Lon R. Greenberg",
            "Lorenzo Simonelli",
            "Lori Koch",
            "Lori Sutton",
            "Lori Sutton, CHRO",
            "Louise S. Sams",
            "Lucio Noto",
            "Lucius Smith Lowe",
            "Luke Nosek",
            "Lydia Beebe",
            "Lynn Martin",
            "Lynne Fitzpatrick",
            "MJ Holthaus",
            "Maamoun Rajeh",
            "Malcolm Fraser",
            "Manuel Kadre",
            "Marc Benioff",
            "Marc D. Miller",
            "Marc E. Binda",
            "Marc N. Casper",
            "Marc Randolph",
            "Marc Rowan",
            "Marc Tarpenning",
            "Marcel Schlumberger",
            "Marcus Goldman",
            "Margaret M. Keane",
            "Maria Black",
            "Mark C. Birk",
            "Mark C. Honeywell",
            "Mark C. Pigott",
            "Mark D. McLaughlin",
            "Mark D. Mclaughlin",
            "Mark D. Millett",
            "Mark G. Papa",
            "Mark J. Costa",
            "Mark J. Parrell",
            "Mark Keim",
            "Mark L. Feidler",
            "Mark Lashier",
            "Mark Mason",
            "Mark Mondello",
            "Mark Papermaster",
            "Mark Parker",
            "Mark R. George",
            "Mark Reuss",
            "Mark Shapiro",
            "Mark Smith",
            "Mark Smucker",
            "Mark W. Begor",
            "Mark W. Kowlzan",
            "Mark Widmar",
            "Mark Zenuk",
            "Mark Zuckerberg",
            "Martin E.",
            "Martin E. Stein Jr.",
            "Martin Eberhard",
            "Martin Fornage",
            "Martin J. Lyons",
            "Martin J. Lyons, Jr.",
            "Martin Kimmel",
            "Martina Cheung",
            "Marvin Ellison",
            "Marvin Sands",
            "Mary Hogan Preusse",
            "Maryann Mannen",
            "Matthew Benger",
            "Matthew Darden",
            "Matthew Flannery",
            "Matthew J. Meloy",
            "Matthew J. White",
            "Matthew Lorber",
            "Matthew Pine",
            "Max Broden",
            "Max Levchin",
            "Maxwell Becton",
            "Meghan Frank",
            "Melanie M. Housey Hart",
            "Melanie M. Housey Hart,",
            "Melvin Simon",
            "Merit Janow",
            "Merritt J. Osborn",
            "Michael \"Mick\" Farrell",
            "Michael A. McNeilly",
            "Michael A. Mcneilly",
            "Michael And Obediah Haymaker",
            "Michael Balmuth",
            "Michael C. Creedon",
            "Michael C. Creedon, Jr.",
            "Michael D. Hsu",
            "Michael D. McKee,",
            "Michael D. Mckee",
            "Michael Dell",
            "Michael Devine",
            "Michael Devine III",
            "Michael Durand",
            "Michael Ettinger",
            "Michael F. Johnston",
            "Michael F. Mahoney",
            "Michael F. Roman",
            "Michael G. O'Grady",
            "Michael G. Ogrady",
            "Michael J. Ahearn",
            "Michael J. Cavanagh",
            "Michael J. Hartshorn",
            "Michael J. Hennigan",
            "Michael J. Mas",
            "Michael Kneeland",
            "Michael Krasny",
            "Michael L. Marberry",
            "Michael L. Marberry, Director",
            "Michael L. Moehn",
            "Michael L. Riordan",
            "Michael M. Calbert",
            "Michael Maguire",
            "Michael Malcolm",
            "Michael McCallister",
            "Michael McMurray",
            "Michael Mccallister",
            "Michael Mcmurray",
            "Michael Mick Farrell",
            "Michael Miebach",
            "Michael P. Lyons",
            "Michael R. Cannon",
            "Michael R. Hsing",
            "Michael Rapino",
            "Michael Rider",
            "Michael Sentonas",
            "Michael Wichterich",
            "Michael Xie",
            "Michael and Obediah Haymaker",
            "Michel A. Khalaf",
            "Michel Lagarde",
            "Michele Buck",
            "Michele Buck Chairwoman",
            "Mick Beekhuizen",
            "Micky Arison",
            "Miguel Patricio",
        ],
    },
    "extraction": {
        # Enhanced quote detection patterns from quotes_enhanced.yaml
        "quote_patterns": [
            {"pattern": '"([^"]*)"', "type": "double_quotes"},
            {"pattern": '«([^»]*)»', "type": "guillemets"},
            {"pattern": "\"([^\"]*)\"", "type": "curly_quotes"},
        ],
        # Minimum and maximum quote lengths
        "min_quote_length": 10,
        "max_quote_length": 10000,

        # Comprehensive keywords for quote relevance filtering
        "keywords": [
            "regulation", "policy", "statement", "violation", "compliance", "law", "rule",
            "settlement", "agreement", "corporate", "company", "executive", "board",
            "shareholder", "stakeholder", "governance", "disclosure", "reporting",
            "fiduciary", "duty", "responsibility", "oversight", "supervision",
            "management", "leadership", "financial", "quarterly", "annual", "earnings",
            "revenue", "profit", "dividend", "stock", "shares", "market", "investment",
            "capital", "privacy", "data", "security", "risk", "ethics", "sustainability",
            "environment", "social", "governance", "compliance", "audit", "internal",
            "controls", "accounting", "finance", "treasury", "tax", "legal", "litigation",
            "arbitration", "mediation", "settlement", "penalty", "fine", "award",
        ],

        # Enhanced speaker attribution from quotes_enhanced.yaml
        "attribution": {
            "enabled": True,
            "max_speaker_distance": 500,
            "speaker_patterns": [
                "said\\s+([^,.:;]+)",
                "stated\\s+([^,.:;]+)",
                "according to\\s+([^,.:;]+)",
                "explained\\s+([^,.:;]+)",
                "noted\\s+([^,.:;]+)",
                "declared\\s+([^,.:;]+)",
                "announced\\s+([^,.:;]+)",
                "reported\\s+([^,.:;]+)",
                "commented\\s+([^,.:;]+)",
                "told\\s+([^,.:;]+)",
            ]
        },

        # Cash amount extraction from outcomes.yaml for financial quotes
        "cash_extraction": {
            "patterns": [
                "\\$[0-9]{1,3}(?:,[0-9]{3})*(?:\\.[0-9]{2})?",
                "[0-9]{1,3}(?:,[0-9]{3})*(?:\\.[0-9]{2})? dollars?",
                "penalty of [0-9]",
                "fine of [0-9]",
                "award of [0-9]",
                "settlement amount",
                "payment of",
            ],
            "normalization": {
                "convert_to_cents": True,
                "handle_ranges": "take_average",
                "currency_symbols": ["$", "USD", "dollars"],
            },
            "validation": {
                "min_amount": 0,
                "max_amount": 1000000000,
                "require_currency": False,
            }
        },

        # Enhanced filtering settings
        "filtering": {
            "remove_duplicates": True,
            "remove_overlaps": True,
            "min_confidence": 0.6,  # Lowered for more coverage
        },

        # Enhanced context extraction
        "context": {
            "before_chars": 250,
            "after_chars": 250,
            "include_speaker": True,
            "include_metadata": True,
        },

        # Performance settings
        "batch_size": 100,
        "max_workers": 4,

        # Comprehensive company aliases for maximum coverage
        "company_aliases": [
            "a. o. smith",
            "aapl",
            "abbott laboratories",
            "abbv",
            "abbvie",
            "abnb",
            "abt",
            "accenture",
            "acgl",
            "acn",
            "adbe",
            "adi",
            "adm",
            "adobe inc.",
            "adp",
            "adsk",
            "advanced micro devices",
            "aee",
            "aep",
            "aes",
            "aes corporation",
            "afl",
            "aflac",
            "agilent technologies",
            "aig",
            "air products",
            "airbnb",
            "aiz",
            "ajg",
            "akam",
            "akamai technologies",
            "alb",
            "albemarle corporation",
            "alexandria real estate equities",
            "algn",
            "align technology",
            "all",
            "alle",
            "allegion",
            "allstate",
            "alphabet inc.",
            "altria",
            "amat",
            "amazon",
            "amcor",
            "amcr",
            "amd",
            "ame",
            "ameren",
            "american electric power",
            "american express",
            "american international group",
            "american tower",
            "american water works",
            "ameriprise financial",
            "ametek",
            "amgen",
            "amgn",
            "amp",
            "amphenol",
            "amt",
            "amzn",
            "analog devices",
            "anet",
            "aon",
            "aon plc",
            "aos",
            "apa",
            "apa corporation",
            "apd",
            "aph",
            "apo",
            "apollo global management",
            "apple inc.",
            "applied materials",
            "aptiv",
            "aptv",
            "arch capital group",
            "archer daniels midland",
            "are",
            "arista networks",
            "arthur j. gallagher & co.",
            "assurant",
            "at&t",
            "atmos energy",
            "ato",
            "autodesk",
            "automatic data processing",
            "autozone",
            "avalonbay communities",
            "avb",
            "avery dennison",
            "avgo",
            "avy",
            "awk",
            "axon",
            "axon enterprise",
            "axp",
            "azo",
            "ba",
            "bac",
            "baker hughes",
            "ball",
            "ball corporation",
            "bank of america",
            "bax",
            "baxter international",
            "bby",
            "bdx",
            "becton dickinson",
            "ben",
            "berkshire hathaway",
            "best buy",
            "bf.b",
            "bg",
            "biib",
            "bio-techne",
            "biogen",
            "bk",
            "bkng",
            "bkr",
            "blackrock",
            "blackstone inc.",
            "bldr",
            "blk",
            "block, inc.",
            "bmy",
            "bny mellon",
            "boeing",
            "booking holdings",
            "boston scientific",
            "br",
            "bristol myers squibb",
            "brk.b",
            "bro",
            "broadcom",
            "broadridge financial solutions",
            "brown & brown",
            "brown–forman",
            "bsx",
            "builders firstsource",
            "bunge global",
            "bx",
            "bxp",
            "bxp, inc.",
            "c.h. robinson",
            "cadence design systems",
            "caesars entertainment",
            "cag",
            "cah",
            "camden property trust",
            "campbell's company (the)",
            "capital one",
            "cardinal health",
            "carmax",
            "carnival",
            "carr",
            "carrier global",
            "cat",
            "caterpillar inc.",
            "cb",
            "cboe",
            "cboe global markets",
            "cbre",
            "cbre group",
            "ccl",
            "cdns",
            "cdw",
            "cdw corporation",
            "ceg",
            "cencora",
            "centene corporation",
            "centerpoint energy",
            "cf",
            "cf industries",
            "cfg",
            "charles river laboratories",
            "charles schwab corporation",
            "charter communications",
            "chd",
            "chevron corporation",
            "chipotle mexican grill",
            "chrw",
            "chtr",
            "chubb limited",
            "church & dwight",
            "ci",
            "cigna",
            "cincinnati financial",
            "cinf",
            "cintas",
            "cisco",
            "citigroup",
            "citizens financial group",
            "cl",
            "clorox",
            "clx",
            "cmcsa",
            "cme",
            "cme group",
            "cmg",
            "cmi",
            "cms",
            "cms energy",
            "cnc",
            "cnp",
            "coca-cola company (the)",
            "cof",
            "cognizant",
            "coin",
            "coinbase",
            "colgate-palmolive",
            "comcast",
            "conagra brands",
            "conocophillips",
            "consolidated edison",
            "constellation brands",
            "constellation energy",
            "coo",
            "cooper companies (the)",
            "cop",
            "copart",
            "cor",
            "corning inc.",
            "corpay",
            "corteva",
            "cost",
            "costar group",
            "costco",
            "coterra",
            "cpay",
            "cpb",
            "cprt",
            "cpt",
            "crl",
            "crm",
            "crowdstrike",
            "crwd",
            "csco",
            "csgp",
            "csx",
            "csx corporation",
            "ctas",
            "ctra",
            "ctsh",
            "ctva",
            "cummins",
            "cvs",
            "cvs health",
            "cvx",
            "czr",
            "d. r. horton",
            "dal",
            "danaher corporation",
            "darden restaurants",
            "dash",
            "datadog",
            "davita",
            "day",
            "dayforce",
            "dd",
            "ddog",
            "de",
            "deck",
            "deckers brands",
            "deere & company",
            "dell",
            "dell technologies",
            "delta air lines",
            "devon energy",
            "dexcom",
            "dg",
            "dgx",
            "dhi",
            "dhr",
            "diamondback energy",
            "digital realty",
            "dis",
            "dlr",
            "dltr",
            "doc",
            "dollar general",
            "dollar tree",
            "dominion energy",
            "domino's",
            "doordash",
            "dov",
            "dover corporation",
            "dow",
            "dow inc.",
            "dpz",
            "dri",
            "dte",
            "dte energy",
            "duk",
            "duke energy",
            "dupont",
            "dva",
            "dvn",
            "dxcm",
            "ea",
            "eastman chemical company",
            "eaton corporation",
            "ebay",
            "ebay inc.",
            "ecl",
            "ecolab",
            "ed",
            "edison international",
            "edwards lifesciences",
            "efx",
            "eg",
            "eix",
            "el",
            "electronic arts",
            "elevance health",
            "elv",
            "emerson electric",
            "emn",
            "emr",
            "enph",
            "enphase energy",
            "entergy",
            "eog",
            "eog resources",
            "epam",
            "epam systems",
            "eqix",
            "eqr",
            "eqt",
            "eqt corporation",
            "equifax",
            "equinix",
            "equity residential",
            "erie",
            "erie indemnity",
            "es",
            "ess",
            "essex property trust",
            "estée lauder companies (the)",
            "etn",
            "etr",
            "everest group",
            "evergy",
            "eversource energy",
            "evrg",
            "ew",
            "exc",
            "exe",
            "exelon",
            "expand energy",
            "expd",
            "expe",
            "expedia group",
            "expeditors international",
            "exr",
            "extra space storage",
            "exxonmobil",
            "f5, inc.",
            "factset",
            "fair isaac",
            "fang",
            "fast",
            "fastenal",
            "fcx",
            "fds",
            "fdx",
            "fe",
            "federal realty investment trust",
            "fedex",
            "ffiv",
            "fi",
            "fico",
            "fidelity national information services",
            "fifth third bancorp",
            "first solar",
            "firstenergy",
            "fis",
            "fiserv",
            "fitb",
            "ford motor company",
            "fortinet",
            "fortive",
            "fox",
            "fox corporation",
            "foxa",
            "franklin resources",
            "freeport-mcmoran",
            "frt",
            "fslr",
            "ftnt",
            "ftv",
            "garmin",
            "gartner",
            "gd",
            "gddy",
            "ge",
            "ge aerospace",
            "ge healthcare",
            "ge vernova",
            "gehc",
            "gen",
            "gen digital",
            "generac",
            "general dynamics",
            "general mills",
            "general motors",
            "genuine parts company",
            "gev",
            "gild",
            "gilead sciences",
            "gis",
            "gl",
            "global payments",
            "globe life",
            "glw",
            "gm",
            "gnrc",
            "godaddy",
            "goldman sachs",
            "goog",
            "googl",
            "gpc",
            "gpn",
            "grmn",
            "gs",
            "gww",
            "hal",
            "halliburton",
            "hartford (the)",
            "has",
            "hasbro",
            "hban",
            "hca",
            "hca healthcare",
            "hd",
            "healthpeak properties",
            "henry schein",
            "hershey company (the)",
            "hewlett packard enterprise",
            "hig",
            "hii",
            "hilton worldwide",
            "hlt",
            "hologic",
            "holx",
            "home depot (the)",
            "hon",
            "honeywell",
            "hormel foods",
            "host hotels & resorts",
            "howmet aerospace",
            "hp inc.",
            "hpe",
            "hpq",
            "hrl",
            "hsic",
            "hst",
            "hsy",
            "hubb",
            "hubbell incorporated",
            "hum",
            "humana",
            "huntington bancshares",
            "huntington ingalls industries",
            "hwm",
            "ibkr",
            "ibm",
            "ice",
            "idex corporation",
            "idexx laboratories",
            "idxx",
            "iex",
            "iff",
            "illinois tool works",
            "incy",
            "incyte",
            "ingersoll rand",
            "intc",
            "intel",
            "interactive brokers",
            "intercontinental exchange",
            "international flavors & fragrances",
            "international paper",
            "interpublic group of companies (the)",
            "intu",
            "intuit",
            "intuitive surgical",
            "invesco",
            "invh",
            "invitation homes",
            "ip",
            "ipg",
            "iqv",
            "iqvia",
            "ir",
            "irm",
            "iron mountain",
            "isrg",
            "it",
            "itw",
            "ivz",
            "j.b. hunt",
            "j.m. smucker company (the)",
            "jabil",
            "jack henry & associates",
            "jacobs solutions",
            "jbht",
            "jbl",
            "jci",
            "jkhy",
            "jnj",
            "johnson & johnson",
            "johnson controls",
            "jpm",
            "jpmorgan chase",
            "kdp",
            "kellanova",
            "kenvue",
            "keurig dr pepper",
            "key",
            "keycorp",
            "keys",
            "keysight technologies",
            "khc",
            "kim",
            "kimberly-clark",
            "kimco realty",
            "kinder morgan",
            "kkr",
            "kkr & co.",
            "kla corporation",
            "klac",
            "kmb",
            "kmi",
            "kmx",
            "ko",
            "kr",
            "kraft heinz",
            "kroger",
            "kvue",
            "l3harris",
            "labcorp",
            "lam research",
            "las vegas sands",
            "ldos",
            "leidos",
            "len",
            "lennar",
            "lennox international",
            "lh",
            "lhx",
            "lii",
            "lilly (eli)",
            "lin",
            "linde plc",
            "live nation entertainment",
            "lkq",
            "lkq corporation",
            "lly",
            "lmt",
            "lockheed martin",
            "loews corporation",
            "low",
            "lowe's",
            "lrcx",
            "lulu",
            "lululemon athletica",
            "luv",
            "lvs",
            "lyb",
            "lyondellbasell",
            "lyv",
            "m&t bank",
            "ma",
            "maa",
            "mar",
            "marathon petroleum",
            "marketaxess",
            "marriott international",
            "marsh mclennan",
            "martin marietta materials",
            "mas",
            "masco",
            "mastercard",
            "match group",
            "mccormick & company",
            "mcd",
            "mcdonald's",
            "mchp",
            "mck",
            "mckesson corporation",
            "mco",
            "mdlz",
            "mdt",
            "medtronic",
            "merck & co.",
            "met",
            "meta",
            "meta platforms",
            "metlife",
            "mettler toledo",
            "mgm",
            "mgm resorts",
            "mhk",
            "microchip technology",
            "micron technology",
            "microsoft",
            "mid-america apartment communities",
            "mkc",
            "mktx",
            "mlm",
            "mmc",
            "mmm",
            "mnst",
            "mo",
            "moderna",
            "moh",
            "mohawk industries",
            "molina healthcare",
            "molson coors beverage company",
            "mondelez international",
            "monolithic power systems",
            "monster beverage",
            "moody's corporation",
            "morgan stanley",
            "mos",
            "mosaic company (the)",
            "motorola solutions",
            "mpc",
            "mpwr",
            "mrk",
            "mrna",
            "ms",
            "msci",
            "msci inc.",
            "msft",
            "msi",
            "mtb",
            "mtch",
            "mtd",
            "mu",
            "nasdaq, inc.",
            "nclh",
            "ndaq",
            "ndsn",
            "nee",
            "nem",
            "netapp",
            "netflix",
            "newmont",
            "news corp",
            "nextera energy",
            "nflx",
            "ni",
            "nike, inc.",
            "nisource",
            "nke",
            "noc",
            "nordson corporation",
            "norfolk southern",
            "northern trust",
            "northrop grumman",
            "norwegian cruise line holdings",
            "now",
            "nrg",
            "nrg energy",
            "nsc",
            "ntap",
            "ntrs",
            "nucor",
            "nue",
            "nvda",
            "nvidia",
            "nvr",
            "nvr, inc.",
            "nws",
            "nwsa",
            "nxp semiconductors",
            "nxpi",
            "occidental petroleum",
            "odfl",
            "oke",
            "old dominion",
            "omc",
            "omnicom group",
            "on",
            "on semiconductor",
            "oneok",
            "oracle corporation",
            "orcl",
            "orly",
            "otis",
            "otis worldwide",
            "oxy",
            "o’reilly automotive",
            "paccar",
            "packaging corporation of america",
            "palantir technologies",
            "palo alto networks",
            "panw",
            "paramount skydance corporation",
            "parker hannifin",
            "payc",
            "paychex",
            "paycom",
            "paypal",
            "payx",
            "pcar",
            "pcg",
            "peg",
            "pentair",
            "pep",
            "pepsico",
            "pfe",
            "pfg",
            "pfizer",
            "pg",
            "pg&e corporation",
            "pgr",
            "ph",
            "philip morris international",
            "phillips 66",
            "phm",
            "pinnacle west capital",
            "pkg",
            "pld",
            "pltr",
            "pm",
            "pnc",
            "pnc financial services",
            "pnr",
            "pnw",
            "pool",
            "pool corporation",
            "ppg",
            "ppg industries",
            "principal financial group",
            "procter & gamble",
            "progressive corporation",
            "prologis",
            "pru",
            "prudential financial",
            "psa",
            "psky",
            "psx",
            "ptc",
            "ptc inc.",
            "public service enterprise group",
            "public storage",
            "pultegroup",
            "pwr",
            "pypl",
            "qcom",
            "qualcomm",
            "quanta services",
            "quest diagnostics",
            "ralph lauren corporation",
            "raymond james financial",
            "rcl",
            "realty income",
            "reg",
            "regency centers",
            "regeneron pharmaceuticals",
            "regions financial corporation",
            "regn",
            "republic services",
            "resmed",
            "revvity",
            "rf",
            "rjf",
            "rl",
            "rmd",
            "rockwell automation",
            "rok",
            "rol",
            "rollins, inc.",
            "rop",
            "roper technologies",
            "ross stores",
            "rost",
            "royal caribbean group",
            "rsg",
            "rtx",
            "rtx corporation",
            "rvty",
            "s&p global",
            "salesforce",
            "sba communications",
            "sbac",
            "sbux",
            "schlumberger",
            "schw",
            "seagate technology",
            "sempra",
            "servicenow",
            "sherwin-williams",
            "shw",
            "simon property group",
            "sjm",
            "skyworks solutions",
            "slb",
            "smci",
            "smurfit westrock",
            "sna",
            "snap-on",
            "snps",
            "so",
            "solv",
            "solventum",
            "southern company",
            "southwest airlines",
            "spg",
            "spgi",
            "sre",
            "stanley black & decker",
            "starbucks",
            "state street corporation",
            "ste",
            "steel dynamics",
            "steris",
            "stld",
            "stryker corporation",
            "stt",
            "stx",
            "stz",
            "supermicro",
            "sw",
            "swk",
            "swks",
            "syf",
            "syk",
            "synchrony financial",
            "synopsys",
            "sysco",
            "syy",
            "t-mobile us",
            "t. rowe price",
            "take-two interactive",
            "tap",
            "tapestry, inc.",
            "targa resources",
            "target corporation",
            "tdg",
            "tdy",
            "te connectivity",
            "tech",
            "tel",
            "teledyne technologies",
            "ter",
            "teradyne",
            "tesla, inc.",
            "texas instruments",
            "texas pacific land corporation",
            "textron",
            "tfc",
            "tgt",
            "thermo fisher scientific",
            "tjx",
            "tjx companies",
            "tko",
            "tko group holdings",
            "tmo",
            "tmus",
            "tpl",
            "tpr",
            "tractor supply",
            "trade desk (the)",
            "trane technologies",
            "transdigm group",
            "travelers companies (the)",
            "trgp",
            "trimble inc.",
            "trmb",
            "trow",
            "truist financial",
            "trv",
            "tsco",
            "tsla",
            "tsn",
            "tt",
            "ttd",
            "ttwo",
            "txn",
            "txt",
            "tyl",
            "tyler technologies",
            "tyson foods",
            "u.s. bancorp",
            "ual",
            "uber",
            "udr",
            "udr, inc.",
            "uhs",
            "ulta",
            "ulta beauty",
            "unh",
            "union pacific corporation",
            "united airlines holdings",
            "united parcel service",
            "united rentals",
            "unitedhealth group",
            "universal health services",
            "unp",
            "ups",
            "uri",
            "usb",
            "valero energy",
            "ventas",
            "veralto",
            "verisign",
            "verisk analytics",
            "verizon",
            "vertex pharmaceuticals",
            "viatris",
            "vici",
            "vici properties",
            "visa inc.",
            "vistra corp",
            "vlo",
            "vlto",
            "vmc",
            "vrsk",
            "vrsn",
            "vrtx",
            "vst",
            "vtr",
            "vtrs",
            "vulcan materials company",
            "vz",
            "w. r. berkley corporation",
            "w. w. grainger",
            "wab",
            "wabtec",
            "walmart",
            "walt disney company (the)",
            "warner bros. discovery",
            "waste management",
            "wat",
            "waters corporation",
            "wbd",
            "wday",
            "wdc",
            "wec",
            "wec energy group",
            "well",
            "wells fargo",
            "welltower",
            "west pharmaceutical services",
            "western digital",
            "weyerhaeuser",
            "wfc",
            "williams companies",
            "williams-sonoma, inc.",
            "willis towers watson",
            "wm",
            "wmb",
            "wmt",
            "workday, inc.",
            "wrb",
            "wsm",
            "wst",
            "wtw",
            "wy",
            "wynn",
            "wynn resorts",
            "xcel energy",
            "xel",
            "xom",
            "xyl",
            "xylem inc.",
            "xyz",
            "yum",
            "yum! brands",
            "zbh",
            "zbra",
            "zebra technologies",
            "zimmer biomet",
            "zoetis",
            "zts",
        ],
        "company_names": [
            "a. o. smith",
            "abbott laboratories",
            "abbvie",
            "accenture",
            "adobe inc.",
            "advanced micro devices",
            "aes corporation",
            "aflac",
            "agilent technologies",
            "air products",
            "airbnb",
            "akamai technologies",
            "albemarle corporation",
            "alexandria real estate equities",
            "align technology",
            "allegion",
            "allstate",
            "alphabet inc.",
            "altria",
            "amazon",
            "amcor",
            "ameren",
            "american electric power",
            "american express",
            "american international group",
            "american tower",
            "american water works",
            "ameriprise financial",
            "ametek",
            "amgen",
            "amphenol",
            "analog devices",
            "aon plc",
            "apa corporation",
            "apollo global management",
            "apple inc.",
            "applied materials",
            "aptiv",
            "arch capital group",
            "archer daniels midland",
            "arista networks",
            "arthur j. gallagher & co.",
            "assurant",
            "at&t",
            "atmos energy",
            "autodesk",
            "automatic data processing",
            "autozone",
            "avalonbay communities",
            "avery dennison",
            "axon enterprise",
            "baker hughes",
            "ball corporation",
            "bank of america",
            "baxter international",
            "becton dickinson",
            "berkshire hathaway",
            "best buy",
            "bio-techne",
            "biogen",
            "blackrock",
            "blackstone inc.",
            "block, inc.",
            "bny mellon",
            "boeing",
            "booking holdings",
            "boston scientific",
            "bristol myers squibb",
            "broadcom",
            "broadridge financial solutions",
            "brown & brown",
            "brown–forman",
            "builders firstsource",
            "bunge global",
            "bxp, inc.",
            "c.h. robinson",
            "cadence design systems",
            "caesars entertainment",
            "camden property trust",
            "campbell's company (the)",
            "capital one",
            "cardinal health",
            "carmax",
            "carnival",
            "carrier global",
            "caterpillar inc.",
            "cboe global markets",
            "cbre group",
            "cdw corporation",
            "cencora",
            "centene corporation",
            "centerpoint energy",
            "cf industries",
            "charles river laboratories",
            "charles schwab corporation",
            "charter communications",
            "chevron corporation",
            "chipotle mexican grill",
            "chubb limited",
            "church & dwight",
            "cigna",
            "cincinnati financial",
            "cintas",
            "cisco",
            "citigroup",
            "citizens financial group",
            "clorox",
            "cme group",
            "cms energy",
            "coca-cola company (the)",
            "cognizant",
            "coinbase",
            "colgate-palmolive",
            "comcast",
            "conagra brands",
            "conocophillips",
            "consolidated edison",
            "constellation brands",
            "constellation energy",
            "cooper companies (the)",
            "copart",
            "corning inc.",
            "corpay",
            "corteva",
            "costar group",
            "costco",
            "coterra",
            "crowdstrike",
            "csx corporation",
            "cummins",
            "cvs health",
            "d. r. horton",
            "danaher corporation",
            "darden restaurants",
            "datadog",
            "davita",
            "dayforce",
            "deckers brands",
            "deere & company",
            "dell technologies",
            "delta air lines",
            "devon energy",
            "dexcom",
            "diamondback energy",
            "digital realty",
            "dollar general",
            "dollar tree",
            "dominion energy",
            "domino's",
            "doordash",
            "dover corporation",
            "dow inc.",
            "dte energy",
            "duke energy",
            "dupont",
            "eastman chemical company",
            "eaton corporation",
            "ebay inc.",
            "ecolab",
            "edison international",
            "edwards lifesciences",
            "electronic arts",
            "elevance health",
            "emerson electric",
            "enphase energy",
            "entergy",
            "eog resources",
            "epam systems",
            "eqt corporation",
            "equifax",
            "equinix",
            "equity residential",
            "erie indemnity",
            "essex property trust",
            "estée lauder companies (the)",
            "everest group",
            "evergy",
            "eversource energy",
            "exelon",
            "expand energy",
            "expedia group",
            "expeditors international",
            "extra space storage",
            "exxonmobil",
            "f5, inc.",
            "factset",
            "fair isaac",
            "fastenal",
            "federal realty investment trust",
            "fedex",
            "fidelity national information services",
            "fifth third bancorp",
            "first solar",
            "firstenergy",
            "fiserv",
            "ford motor company",
            "fortinet",
            "fortive",
            "fox corporation",
            "franklin resources",
            "freeport-mcmoran",
            "garmin",
            "gartner",
            "ge aerospace",
            "ge healthcare",
            "ge vernova",
            "gen digital",
            "generac",
            "general dynamics",
            "general mills",
            "general motors",
            "genuine parts company",
            "gilead sciences",
            "global payments",
            "globe life",
            "godaddy",
            "goldman sachs",
            "halliburton",
            "hartford (the)",
            "hasbro",
            "hca healthcare",
            "healthpeak properties",
            "henry schein",
            "hershey company (the)",
            "hewlett packard enterprise",
            "hilton worldwide",
            "hologic",
            "home depot (the)",
            "honeywell",
            "hormel foods",
            "host hotels & resorts",
            "howmet aerospace",
            "hp inc.",
            "hubbell incorporated",
            "humana",
            "huntington bancshares",
            "huntington ingalls industries",
            "ibm",
            "idex corporation",
            "idexx laboratories",
            "illinois tool works",
            "incyte",
            "ingersoll rand",
            "intel",
            "interactive brokers",
            "intercontinental exchange",
            "international flavors & fragrances",
            "international paper",
            "interpublic group of companies (the)",
            "intuit",
            "intuitive surgical",
            "invesco",
            "invitation homes",
            "iqvia",
            "iron mountain",
            "j.b. hunt",
            "j.m. smucker company (the)",
            "jabil",
            "jack henry & associates",
            "jacobs solutions",
            "johnson & johnson",
            "johnson controls",
            "jpmorgan chase",
            "kellanova",
            "kenvue",
            "keurig dr pepper",
            "keycorp",
            "keysight technologies",
            "kimberly-clark",
            "kimco realty",
            "kinder morgan",
            "kkr & co.",
            "kla corporation",
            "kraft heinz",
            "kroger",
            "l3harris",
            "labcorp",
            "lam research",
            "las vegas sands",
            "leidos",
            "lennar",
            "lennox international",
            "lilly (eli)",
            "linde plc",
            "live nation entertainment",
            "lkq corporation",
            "lockheed martin",
            "loews corporation",
            "lowe's",
            "lululemon athletica",
            "lyondellbasell",
            "m&t bank",
            "marathon petroleum",
            "marketaxess",
            "marriott international",
            "marsh mclennan",
            "martin marietta materials",
            "masco",
            "mastercard",
            "match group",
            "mccormick & company",
            "mcdonald's",
            "mckesson corporation",
            "medtronic",
            "merck & co.",
            "meta platforms",
            "metlife",
            "mettler toledo",
            "mgm resorts",
            "microchip technology",
            "micron technology",
            "microsoft",
            "mid-america apartment communities",
            "moderna",
            "mohawk industries",
            "molina healthcare",
            "molson coors beverage company",
            "mondelez international",
            "monolithic power systems",
            "monster beverage",
            "moody's corporation",
            "morgan stanley",
            "mosaic company (the)",
            "motorola solutions",
            "msci inc.",
            "nasdaq, inc.",
            "netapp",
            "netflix",
            "newmont",
            "news corp",
            "nextera energy",
            "nike, inc.",
            "nisource",
            "nordson corporation",
            "norfolk southern",
            "northern trust",
            "northrop grumman",
            "norwegian cruise line holdings",
            "nrg energy",
            "nucor",
            "nvidia",
            "nvr, inc.",
            "nxp semiconductors",
            "occidental petroleum",
            "old dominion",
            "omnicom group",
            "on semiconductor",
            "oneok",
            "oracle corporation",
            "otis worldwide",
            "o’reilly automotive",
            "paccar",
            "packaging corporation of america",
            "palantir technologies",
            "palo alto networks",
            "paramount skydance corporation",
            "parker hannifin",
            "paychex",
            "paycom",
            "paypal",
            "pentair",
            "pepsico",
            "pfizer",
            "pg&e corporation",
            "philip morris international",
            "phillips 66",
            "pinnacle west capital",
            "pnc financial services",
            "pool corporation",
            "ppg industries",
            "principal financial group",
            "procter & gamble",
            "progressive corporation",
            "prologis",
            "prudential financial",
            "ptc inc.",
            "public service enterprise group",
            "public storage",
            "pultegroup",
            "qualcomm",
            "quanta services",
            "quest diagnostics",
            "ralph lauren corporation",
            "raymond james financial",
            "realty income",
            "regency centers",
            "regeneron pharmaceuticals",
            "regions financial corporation",
            "republic services",
            "resmed",
            "revvity",
            "rockwell automation",
            "rollins, inc.",
            "roper technologies",
            "ross stores",
            "royal caribbean group",
            "rtx corporation",
            "s&p global",
            "salesforce",
            "sba communications",
            "schlumberger",
            "seagate technology",
            "sempra",
            "servicenow",
            "sherwin-williams",
            "simon property group",
            "skyworks solutions",
            "smurfit westrock",
            "snap-on",
            "solventum",
            "southern company",
            "southwest airlines",
            "stanley black & decker",
            "starbucks",
            "state street corporation",
            "steel dynamics",
            "steris",
            "stryker corporation",
            "supermicro",
            "synchrony financial",
            "synopsys",
            "sysco",
            "t-mobile us",
            "t. rowe price",
            "take-two interactive",
            "tapestry, inc.",
            "targa resources",
            "target corporation",
            "te connectivity",
            "teledyne technologies",
            "teradyne",
            "tesla, inc.",
            "texas instruments",
            "texas pacific land corporation",
            "textron",
            "thermo fisher scientific",
            "tjx companies",
            "tko group holdings",
            "tractor supply",
            "trade desk (the)",
            "trane technologies",
            "transdigm group",
            "travelers companies (the)",
            "trimble inc.",
            "truist financial",
            "tyler technologies",
            "tyson foods",
            "u.s. bancorp",
            "uber",
            "udr, inc.",
            "ulta beauty",
            "union pacific corporation",
            "united airlines holdings",
            "united parcel service",
            "united rentals",
            "unitedhealth group",
            "universal health services",
            "valero energy",
            "ventas",
            "veralto",
            "verisign",
            "verisk analytics",
            "verizon",
            "vertex pharmaceuticals",
            "viatris",
            "vici properties",
            "visa inc.",
            "vistra corp",
            "vulcan materials company",
            "w. r. berkley corporation",
            "w. w. grainger",
            "wabtec",
            "walmart",
            "walt disney company (the)",
            "warner bros. discovery",
            "waste management",
            "waters corporation",
            "wec energy group",
            "wells fargo",
            "welltower",
            "west pharmaceutical services",
            "western digital",
            "weyerhaeuser",
            "williams companies",
            "williams-sonoma, inc.",
            "willis towers watson",
            "workday, inc.",
            "wynn resorts",
            "xcel energy",
            "xylem inc.",
            "yum! brands",
            "zebra technologies",
            "zimmer biomet",
            "zoetis",
        ],
        "min_quote_length": "15",
        "max_quote_length": "5000",
    },
    "reranking": {
        # Enhanced reranking with better threshold for more coverage
        "enabled": True,
        "model": "all-mpnet-base-v2",
        "threshold": 0.5,  # Lowered for more coverage
        "seed_quotes": [
            "The company stated that",
            "According to the CEO",
            "The corporation announced",
            "In a statement, the executive said",
            "The board of directors noted",
            "According to company policy",
            "The spokesperson explained",
            "Corporate regulations require",
            "The executive team decided",
            "Shareholders were informed that",
            "The chairman declared",
            "Company leadership stated",
            "The CFO reported that",
            "Board members agreed that",
            "Corporate governance requires",
            "The company reported",
            "Financial results show",
            "Market conditions indicate",
            "Regulatory compliance requires",
            "The board approved",
            # Additional seed quotes for better semantic matching
            "The CEO explained",
            "Executive leadership stated",
            "Corporate policy requires",
            "Board governance mandates",
            "Shareholder interests require",
            "Regulatory oversight demands",
            "Financial reporting standards",
            "Compliance requirements state",
        ],
        # Quality thresholds
        "min_semantic_score": 0.55,  # Lowered for more coverage
        "max_redundancy_score": 0.85,
    },
    "filtering": {
        # Enhanced heuristics for better quality control
        "heuristics": [
            {"name": "speaker_required", "enabled": True, "threshold": 0.75},  # Slightly lowered for more coverage
            {"name": "context_quality", "enabled": True, "threshold": 0.65},
            {"name": "length_appropriate", "enabled": True, "min_length": 15, "max_length": 5000},
            {"name": "corporate_relevance", "enabled": True, "threshold": 0.5},  # Lowered for more coverage
            {"name": "executive_name_match", "enabled": True, "threshold": 0.8},
            {"name": "company_alias_match", "enabled": True, "threshold": 0.7},
        ],
        # Legal document specific filters
        "legal_filters": {
            "court_opinions_only": False,
            "include_dissents": True,
            "include_concurrences": True,
            "exclude_routine_matters": True,
        },
    },

    # Enhanced validation settings
    "validation": {
        "require_quote_id": True,
        "require_doc_id": True,
        "require_span": True,
        "validate_offsets": True,
        "check_consistency": True,
    },

    # S&P 500 and Dow Jones Integration Metadata
    "sp500_dow_integration": {
        "enabled": True,
        "executives_loaded": 1756,  # From comprehensive.py
        "companies_loaded": 494,
        "company_aliases_loaded": 980,
        "roles_loaded": 67,
        "config_version": "3.0",
        "last_updated": "2025-01-01",
        "sources": [
            "sp500_key_people_people.csv",
            "sp500_key_people_companies.csv",
            "sp500_key_people_appointments.csv",
            "sp500_key_people_roles.csv",
            "dow_key_people_people.csv",
            "dow_key_people_companies.csv",
            "dow_key_people_appointments.csv",
            "dow_key_people_roles.csv",
        ],
        "top_companies": [
            "American Water Works",
            "Alphabet Inc.",
            "PayPal",
            "West Pharmaceutical Services",
            "Arch Capital Group",
            "Apple Inc.",
            "Microsoft",
            "Amazon",
            "NVIDIA",
            "Tesla",
        ],
    },
    "performance": {
        "batch_size": "100",
        "max_workers": "4",
        "enable_caching": "True",
        "cache_ttl": "3600",
    },
    "sp500_dow_integration": {
        "enabled": "True",
        "executives_loaded": "1756",
        "companies_loaded": "494",
        "company_aliases_loaded": "980",
        "roles_loaded": "67",
        "config_version": "2.0",
        "last_updated": "2025-01-01",
        "sources": [
            "sp500_key_people_people.csv",
            "sp500_key_people_companies.csv",
            "sp500_key_people_appointments.csv",
            "sp500_key_people_roles.csv",
            "dow_key_people_people.csv",
            "dow_key_people_companies.csv",
            "dow_key_people_appointments.csv",
            "dow_key_people_roles.csv",
        ],
    },
}
