name: ci

on:
  pull_request:
    paths:
      - "packages/**"
      - ".github/workflows/**"
  push:
    branches: ["main"]
  workflow_dispatch: {}
  schedule:
    - cron: "0 8 * * *"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fast:
    name: Fast checks (lint, typecheck, unit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: uv sync --dev
      - name: Black
        run: uv run black --check .
      - name: isort
        run: uv run isort --check-only .
      - name: mypy
        run: uv run mypy .
      - name: flake8
        run: uv run flake8 .
      - name: Unit tests (excluding e2e)
        run: uv run pytest -q -k "not e2e"

  e2e:
    name: E2E / integration (non-blocking)
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: uv sync --dev
      - name: Run e2e tests
        run: uv run pytest -q tests/test_e2e_data.py
